import { Disposer, on, query, safeJsonParse, text } from './browser-platform.ts';

export const CHAT_EXPORT_STORAGE_KEY = 'hafize.conversations.v1';
export const CHAT_EXPORT_LIMITS = Object.freeze({ maxMarkdownChars: 2_000_000, maxJsonChars: 2_000_000 });
export type ExportConversation = { title?: unknown; messages?: unknown };

export function safeText(value: unknown): string { return typeof value === 'string' ? value : ''; }
export function readConversations(storage: Storage = localStorage): ExportConversation[] { const value=safeJsonParse<unknown>(storage.getItem(CHAT_EXPORT_STORAGE_KEY),[]); return Array.isArray(value)?value.filter((item):item is ExportConversation=>Boolean(item&&typeof item==='object')):[]; }
export function buildMarkdown(conversations: ExportConversation[]): string { const lines=['# Hafize sohbet geçmişi','',`Dışa aktarma tarihi: ${new Date().toLocaleString('tr-TR')}`,'']; for(const [index,conversation] of conversations.entries()){ lines.push(`## ${index+1}. ${safeText(conversation.title)||'Yeni sohbet'}`,''); const messages=Array.isArray(conversation.messages)?conversation.messages:[]; for(const message of messages){ if(!message||typeof message!=='object')continue; const data=message as {role?:unknown;content?:unknown}; const content=safeText(data.content).trim(); if(!content)continue; lines.push(`### ${data.role==='assistant'?'Hafize':'Sen'}`,'',content,''); } lines.push('---',''); } return lines.join('\n').slice(0,CHAT_EXPORT_LIMITS.maxMarkdownChars); }
export function buildJson(conversations: ExportConversation[]): string { return JSON.stringify({exportedAt:new Date().toISOString(),version:1,conversations},null,2).slice(0,CHAT_EXPORT_LIMITS.maxJsonChars); }

export function mountChatHistoryExport(documentRef:Document=document,rootRef:Window=window):Readonly<{markdown:()=>string;json:()=>string;destroy:()=>void}>|null{
 const block=query<HTMLElement>(documentRef,'.history-block');const history=query<HTMLElement>(documentRef,'#conversationList');if(!block||!history||documentRef.getElementById('typedHistoryExport'))return null;const disposer=new Disposer();const wrap=text<HTMLElement>(documentRef,'div','','history-export');wrap.id='typedHistoryExport';const label=text<HTMLElement>(documentRef,'span','Dışa aktar','history-export-label');const actions=text<HTMLElement>(documentRef,'div','','history-export-actions');
 const announce=(message:string)=>{const toast=query<HTMLElement>(documentRef,'#toast');if(!toast)return;toast.textContent=message;toast.classList.remove('hidden');const timer=Number(toast.dataset.typedExportTimer||0);if(timer)rootRef.clearTimeout(timer);toast.dataset.typedExportTimer=String(rootRef.setTimeout(()=>toast.classList.add('hidden'),3200));};
 const download=(content:string,filename:string,type:string)=>{try{const blob=new Blob([content],{type});const url=rootRef.URL.createObjectURL(blob);const anchor=documentRef.createElement('a');anchor.href=url;anchor.download=filename;anchor.rel='noopener';documentRef.body.append(anchor);anchor.click();anchor.remove();rootRef.setTimeout(()=>rootRef.URL.revokeObjectURL(url),1000);return true;}catch{return false;}};
 const add=(format:'md'|'json')=>{const button=text<HTMLButtonElement>(documentRef,'button',format==='md'?'Markdown':'JSON','history-export-btn');button.type='button';button.setAttribute('aria-label',`Sohbet geçmişini ${format==='md'?'Markdown':'JSON'} olarak dışa aktar`);on(button,'click',()=>{const conversations=readConversations(rootRef.localStorage);if(!conversations.length){announce('Dışa aktarılacak sohbet geçmişi yok.');return;}const content=format==='md'?buildMarkdown(conversations):buildJson(conversations);const filename=`hafize-sohbet-gecmisi-${new Date().toISOString().slice(0,10)}.${format}`;const type=format==='md'?'text/markdown;charset=utf-8':'application/json;charset=utf-8';announce(download(content,filename,type)?`${format==='md'?'Markdown':'JSON'} dosyası hazırlandı.`:'Dışa aktarma başlatılamadı.');},undefined,disposer);actions.append(button);};
 add('md');add('json');wrap.append(label,actions);block.insertBefore(wrap,history);return Object.freeze({markdown:()=>buildMarkdown(readConversations(rootRef.localStorage)),json:()=>buildJson(readConversations(rootRef.localStorage)),destroy:()=>disposer.flush()}); }

const start=()=>mountChatHistoryExport(document,window);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
