import { Disposer, on, query, safeJsonParse, boundedText, text } from './browser-platform.ts';

export const CONVERSATION_WORKSPACE_KEYS = Object.freeze({ data: 'hafize.conversations.v1', state: 'hafize.conversation-workspace.v1' });
export const CONVERSATION_WORKSPACE_LIMITS = Object.freeze({ conversations: 30, title: 80, tag: 24, tags: 8, importBytes: 1024 * 1024, importConversations: 30, importMessages: 200, message: 12000, exportSelection: 30 });
export type ConversationFilter = 'all' | 'active' | 'archived' | 'pinned' | 'tagged';
export type ConversationSort = 'updated-desc' | 'updated-asc' | 'title-asc' | 'created-desc' | 'created-asc';
export type WorkspaceState = { filter: ConversationFilter; sort: ConversationSort; tag: string; query: string; selected: string[] };
export type ConversationRecord = { id: string; title: string; agentId: string; toolsEnabled: boolean; archived: boolean; pinned: boolean; tags: string[]; createdAt: string; updatedAt: string; messages: Array<{ id: string; role: 'user' | 'assistant'; content: string; at: string; toolActivities?: Array<{ label: string; state: string }> }> };

export const DEFAULT_WORKSPACE_STATE: WorkspaceState = Object.freeze({ filter: 'all', sort: 'updated-desc', tag: '', query: '', selected: [] });

export function normalizeText(value: unknown): string { return typeof value === 'string' ? value.replace(/\s+/g, ' ').trim().toLocaleLowerCase('tr-TR') : ''; }
export function cleanTitle(value: unknown): string { return String(value ?? '').replace(/\s+/g, ' ').trim().slice(0, CONVERSATION_WORKSPACE_LIMITS.title) || 'Yeni sohbet'; }
export function cleanTag(value: unknown): string { return String(value ?? '').replace(/\s+/g, ' ').trim().replace(/^#+\s*/, '').slice(0, CONVERSATION_WORKSPACE_LIMITS.tag); }
export function normalizeState(value: unknown): WorkspaceState { const input=value&&typeof value==='object'?value as Record<string,unknown>:{}; const filter=['all','active','archived','pinned','tagged'].includes(String(input.filter))?String(input.filter) as ConversationFilter:'all'; const sort=['updated-desc','updated-asc','title-asc','created-desc','created-asc'].includes(String(input.sort))?String(input.sort) as ConversationSort:'updated-desc'; const tag=typeof input.tag==='string'?cleanTag(input.tag):''; const query=typeof input.query==='string'?normalizeText(input.query).slice(0,120):''; const selected=Array.isArray(input.selected)?input.selected.filter((id):id is string=>typeof id==='string').slice(0,CONVERSATION_WORKSPACE_LIMITS.conversations):[]; return {filter,sort,tag,query,selected}; }
export function readConversations(storage: Storage = localStorage): ConversationRecord[] { const value=safeJsonParse<unknown>(storage.getItem(CONVERSATION_WORKSPACE_KEYS.data),[]); return normalizeConversationList(value); }
export function normalizeConversationList(value: unknown): ConversationRecord[] { if(!Array.isArray(value)) return []; const seen=new Set<string>(); const output:ConversationRecord[]=[]; value.forEach((raw,index)=>{ if(!raw||typeof raw!=='object') return; const input=raw as Record<string,unknown>; const id=typeof input.id==='string'?input.id.trim().slice(0,120):''; if(!id||seen.has(id)) return; seen.add(id); const messages=Array.isArray(input.messages)?input.messages.slice(0,CONVERSATION_WORKSPACE_LIMITS.importMessages).map((message,mi)=>{ if(!message||typeof message!=='object') return null; const m=message as Record<string,unknown>; const content=typeof m.content==='string'?m.content.slice(0,CONVERSATION_WORKSPACE_LIMITS.message):''; if(!content) return null; return { id:typeof m.id==='string'&&m.id?m.id.slice(0,120):`imported-${index}-${mi}`, role:m.role==='assistant'?'assistant':'user' as 'user', content, at:typeof m.at==='string'?m.at:new Date().toISOString(), toolActivities:Array.isArray(m.toolActivities)?m.toolActivities.slice(0,4).filter(Boolean).map((activity)=>({label:boundedText((activity as any)?.label,80),state:String((activity as any)?.state||'success')})):undefined }; }).filter(Boolean) as ConversationRecord['messages']:[]; const tags=Array.isArray(input.tags)?[...new Set(input.tags.map(cleanTag).filter(Boolean))].slice(0,CONVERSATION_WORKSPACE_LIMITS.tags):[]; const date=(value:unknown, fallback:number)=>{const time=Date.parse(String(value||''));return Number.isFinite(time)?new Date(time).toISOString():new Date(fallback).toISOString();}; output.push({id,title:cleanTitle(input.title),agentId:typeof input.agentId==='string'?input.agentId.slice(0,120):'',toolsEnabled:input.toolsEnabled===true,archived:input.archived===true,pinned:input.pinned===true,tags,createdAt:date(input.createdAt,Date.now()-index),updatedAt:date(input.updatedAt,Date.now()-index),messages}); }); return output.slice(0,CONVERSATION_WORKSPACE_LIMITS.conversations); }
export function sortConversations(conversations: ConversationRecord[], sort: ConversationSort): ConversationRecord[] { const output=conversations.slice(); const collator=new Intl.Collator('tr-TR',{sensitivity:'base',numeric:true}); output.sort((a,b)=>{if(sort==='title-asc')return collator.compare(a.title,b.title); const left=Date.parse(sort.startsWith('created')?a.createdAt:a.updatedAt)||0; const right=Date.parse(sort.startsWith('created')?b.createdAt:b.updatedAt)||0; return sort.endsWith('asc')?left-right:right-left;}); return output; }
export function matchesConversation(conversation: ConversationRecord, state: WorkspaceState): boolean { if(state.filter==='active'&&conversation.archived)return false; if(state.filter==='archived'&&!conversation.archived)return false; if(state.filter==='pinned'&&!conversation.pinned)return false; if(state.filter==='tagged'&&!conversation.tags.length)return false; if(state.tag&&!conversation.tags.some((tag)=>normalizeText(tag)===state.tag))return false; if(!state.query)return true; const haystack=normalizeText([conversation.title,conversation.agentId,...conversation.tags,...conversation.messages.map((message)=>message.content)].join(' ')); return haystack.includes(state.query); }
export function filterConversations(conversations: ConversationRecord[], state: WorkspaceState): ConversationRecord[] { return sortConversations(conversations.filter((item)=>matchesConversation(item,state)),state.sort); }
export function collectTags(conversations: ConversationRecord[]): Array<{ label:string; count:number }> { const tags=new Map<string,{label:string;count:number}>(); for(const conversation of conversations)for(const raw of conversation.tags){const label=cleanTag(raw);if(!label)continue;const key=normalizeText(label);const entry=tags.get(key)||{label,count:0};entry.count++;tags.set(key,entry);} return [...tags.values()].sort((a,b)=>b.count-a.count||a.label.localeCompare(b.label,'tr-TR')); }

function makeButton(documentRef:Document,label:string,aria:string,className='workspace-ghost'):HTMLButtonElement{const node=text<HTMLButtonElement>(documentRef,'button',label,className);node.type='button';node.setAttribute('aria-label',aria);return node;}
function readState(storage:Storage):WorkspaceState{try{return normalizeState(safeJsonParse<unknown>(storage.getItem(CONVERSATION_WORKSPACE_KEYS.state),{}));}catch{return {...DEFAULT_WORKSPACE_STATE,selected:[]};}}
function writeState(storage:Storage,state:WorkspaceState):void{try{storage.setItem(CONVERSATION_WORKSPACE_KEYS.state,JSON.stringify(normalizeState(state)));}catch{}}
function normalizeImportedPayload(value:unknown):ConversationRecord[]{if(Array.isArray(value))return normalizeConversationList(value);if(value&&typeof value==='object')return normalizeConversationList((value as Record<string,unknown>).conversations);return [];}
function exportSelection(conversations:ConversationRecord[]):string{const payload={version:1,source:'hafize-conversation-workspace',exportedAt:new Date().toISOString(),conversations:normalizeConversationList(conversations)};return JSON.stringify(payload,null,2).slice(0,CONVERSATION_WORKSPACE_LIMITS.importBytes);}

export function mountConversationWorkspace(documentRef:Document=document,rootRef:Window=window):Readonly<{getState:()=>WorkspaceState;setState:(next:Partial<WorkspaceState>)=>void;refresh:()=>void;destroy:()=>void}>|null{
 const block=query<HTMLElement>(documentRef,'.history-block');const history=query<HTMLElement>(documentRef,'#conversationList');if(!block||!history)return null;
 const storage=rootRef.localStorage;const disposer=new Disposer();let state=readState(storage);let mounted=true;
 const toolbar=text<HTMLElement>(documentRef,'section','','conversation-workspace');toolbar.setAttribute('aria-label','Sohbet çalışma alanı');const heading=text<HTMLElement>(documentRef,'strong','Sohbet çalışma alanı','conversation-workspace-title');const search=documentRef.createElement('input');search.type='search';search.placeholder='Başlık, etiket veya mesaj…';search.maxLength=120;search.setAttribute('aria-label','Sohbet çalışma alanında ara');const filter=documentRef.createElement('select');filter.setAttribute('aria-label','Sohbet filtresi');[['all','Tüm sohbetler'],['active','Arşivlenmemiş'],['archived','Arşivlenmiş'],['pinned','Sabitlenmiş'],['tagged','Etiketli']].forEach(([v,l])=>filter.append(new Option(l,v)));const sort=documentRef.createElement('select');sort.setAttribute('aria-label','Sohbet sıralaması');[['updated-desc','Son güncellenen'],['updated-asc','En eski güncellenen'],['title-asc','Başlığa göre'],['created-desc','Yeni oluşturulan'],['created-asc','Eski oluşturulan']].forEach(([v,l])=>sort.append(new Option(l,v)));const tag=documentRef.createElement('select');tag.setAttribute('aria-label','Etikete göre filtrele');const status=text<HTMLElement>(documentRef,'span','','conversation-workspace-status');const actions=text<HTMLElement>(documentRef,'div','','conversation-workspace-actions');const selectAll=makeButton(documentRef,'Tümünü seç','Görünen sohbetlerin tamamını seç');const clear=makeButton(documentRef,'Seçimi temizle','Sohbet seçimini temizle');actions.append(selectAll,clear);toolbar.append(heading,search,filter,sort,tag,actions,status);block.insertBefore(toolbar,history);
 const syncTagOptions=()=>{tag.replaceChildren(new Option('Tüm etiketler',''));for(const item of collectTags(readConversations(storage)))tag.append(new Option(`${item.label} · ${item.count}`,normalizeText(item.label)));tag.value=state.tag;};
 const updateRows=()=>{const conversations=readConversations(storage);const visible=filterConversations(conversations,state);const visibleIds=new Set(visible.map((item)=>item.id));const rows=[...history.querySelectorAll<HTMLElement>('.conversation-row')];rows.forEach((row)=>{const id=row.querySelector('.conversation-open')?.getAttribute('data-conversation-id')||'';row.hidden=Boolean(id)&&!visibleIds.has(id);const checkbox=row.querySelector<HTMLInputElement>('input[data-conversation-selection]');if(checkbox){checkbox.checked=state.selected.includes(id);}});const selected=state.selected.filter((id)=>conversations.some((item)=>item.id===id));state.selected=selected;status.textContent=`${visible.length}/${conversations.length} sohbet · ${selected.length} seçili`;syncTagOptions();};
 const persist=()=>{writeState(storage,state);updateRows();};
 const setState=(next:Partial<WorkspaceState>)=>{state=normalizeState({...state,...next,selected:next.selected??state.selected});persist();};
 const visibleIds=()=>filterConversations(readConversations(storage),state).map((item)=>item.id);
 const onSelectAll=()=>{state.selected=visibleIds().slice(0,CONVERSATION_WORKSPACE_LIMITS.conversations);persist();}; const onClear=()=>{state.selected=[];persist();};
 on(search,'input',()=>setState({query:search.value}),undefined,disposer);on(filter,'change',()=>setState({filter:filter.value as ConversationFilter}),undefined,disposer);on(sort,'change',()=>setState({sort:sort.value as ConversationSort}),undefined,disposer);on(tag,'change',()=>setState({tag:tag.value}),undefined,disposer);on(selectAll,'click',onSelectAll,undefined,disposer);on(clear,'click',onClear,undefined,disposer);
 const observer=new MutationObserver(()=>updateRows());observer.observe(history,{childList:true,subtree:true});disposer.add(()=>observer.disconnect());on(rootRef,'storage',((event:Event)=>{if((event as StorageEvent).key===CONVERSATION_WORKSPACE_KEYS.data||((event as StorageEvent).key===CONVERSATION_WORKSPACE_KEYS.state)) {state=readState(storage);refresh();}})as EventListener,undefined,disposer);
 const refresh=()=>{if(!mounted)return;search.value=state.query;filter.value=state.filter;sort.value=state.sort;updateRows();};refresh();
 return Object.freeze({getState:()=>({...state,selected:[...state.selected]}),setState,refresh,destroy:()=>{mounted=false;disposer.flush();toolbar.remove();}});
}

const start=()=>mountConversationWorkspace(document,window);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
