import { Disposer, on, query, boundedText } from './browser-platform.ts';

export const HANDS_FREE_DEFAULT_WAKE_PHRASE = 'hafize';
export const HANDS_FREE_LIMITS = Object.freeze({ restartDelay: 350, handoffTimeout: 1500, cooldown: 1800, session: 30 * 60 * 1000 });
export const HANDS_FREE_RETRY_DELAYS = Object.freeze([2000, 5000, 15000, 30000, 60000]);
export const HANDS_FREE_EVENTS = Object.freeze({ input: 'hafize:voice-input-state', output: 'hafize:voice-output-state', revoke: 'hafize:hands-free-revoke' });

export type RecognitionKind = 'aborted' | 'idle' | 'network' | 'terminal';
export function getRecognitionConstructor(root: Window): any { return (root as any).SpeechRecognition || (root as any).webkitSpeechRecognition || null; }
export function normalizeSpeech(value: unknown): string { return typeof value === 'string' ? value.normalize('NFKC').toLocaleLowerCase('tr-TR').replace(/[^\p{L}\p{N}\s]/gu, ' ').replace(/\s+/g,' ').trim() : ''; }
export function containsWakePhrase(value: string, wakePhrase = HANDS_FREE_DEFAULT_WAKE_PHRASE): boolean { const speech=normalizeSpeech(value); const wake=normalizeSpeech(wakePhrase); if(!speech||!wake)return false; return wake.includes(' ') ? ` ${speech} `.includes(` ${wake} `) : speech.split(' ').includes(wake); }
export function normalizeRecognitionError(value: unknown): string { return typeof value==='string'?value.trim().toLocaleLowerCase('en-US').replace(/_/g,'-'):'unknown'; }
export function classifyRecognitionError(value: unknown): { code: string; kind: RecognitionKind } { const code=normalizeRecognitionError(value); if(code==='aborted')return{code,kind:'aborted'};if(code==='no-speech')return{code,kind:'idle'};if(code==='network')return{code,kind:'network'};return{code,kind:'terminal'}; }
export function networkRetryDelay(streak: number): number { if(!Number.isInteger(streak)||st<1)return 0; return HANDS_FREE_RETRY_DELAYS[Math.min(streak,HANDS_FREE_RETRY_DELAYS.length)-1] || 0; }
export function terminalRecognitionMessage(code: string): string { if(code==='audio-capture')return 'Eller serbest mikrofonu kullanamadı. Mikrofonu kontrol edip yeniden aç.';if(['not-allowed','service-not-allowed','security'].includes(code))return 'Eller serbest için mikrofon izni kullanılamıyor. İzni kontrol edip yeniden aç.';if(code==='language-not-supported')return 'Eller serbest konuşma dili bu tarayıcıda desteklenmiyor.';return 'Eller serbest konuşma tanıma hatası nedeniyle kapatıldı. Devam etmek için yeniden aç.'; }
export function readRecognitionText(event: any): string { if(!event?.results)return '';const chunks:string[]=[];const start=Number.isInteger(event.resultIndex)?event.resultIndex:0;for(let i=start;i<event.results.length;i++){const value=event.results[i]?.[0]?.transcript;if(typeof value==='string')chunks.push(value);}return chunks.join(' ').trim(); }

export function mountHandsFree(documentRef: Document=document,rootRef:Window=window):Readonly<{isSupported:boolean;isEnabled:()=>boolean;isListening:()=>boolean;setEnabled:(value:boolean)=>void;destroy:()=>void}>|null{
 const toggle=query<HTMLButtonElement>(documentRef,'#handsFreeToggle');const indicator=query<HTMLElement>(documentRef,'#handsFreeIndicator');const mic=query<HTMLButtonElement>(documentRef,'#micBtn');const input=query<HTMLTextAreaElement>(documentRef,'#messageInput');const toast=query<HTMLElement>(documentRef,'#toast');if(!toggle||!indicator||!mic||!input)return null;
 const Recognition=getRecognitionConstructor(rootRef);const disposer=new Disposer();let enabled=false;let listening=false;let recognition:any=null;let restartTimer=0;let handoffTimer=0;let sessionTimer=0;let cooldownTimer=0;let handoffWaiting=false;let coolingDown=false;let voiceInputListening=false;let voiceOutputSpeaking=false;let networkStreak=0;let destroyed=false;
 const announce=(message:string)=>{if(!toast||!message)return;toast.textContent=boundedText(message,240);toast.classList.remove('hidden');};
 const clear=(kind:'restart'|'handoff'|'session'|'cooldown')=>{const id=kind==='restart'?restartTimer:kind==='handoff'?handoffTimer:kind==='session'?sessionTimer:cooldownTimer;if(id)rootRef.clearTimeout(id);if(kind==='restart')restartTimer=0;if(kind==='handoff')handoffTimer=0;if(kind==='session')sessionTimer=0;if(kind==='cooldown')cooldownTimer=0;if(kind==='handoff')handoffWaiting=false;if(kind==='cooldown')coolingDown=false;};
 const render=()=>{toggle.disabled=!Recognition||input.disabled;toggle.setAttribute('aria-pressed',String(enabled));toggle.textContent=enabled?'Eller serbest açık':'Eller serbest kapalı';indicator.hidden=!enabled;indicator.textContent=enabled?(voiceInputListening?'○ Sesli giriş etkin':handoffWaiting?'○ Sesli giriş hazırlanıyor':voiceOutputSpeaking?'○ Hafize konuşuyor':coolingDown?'○ Yankı koruması etkin':listening?'● “Hafize” için dinliyor':'○ Eller serbest beklemede'):'';indicator.dataset.listening=String(listening);indicator.dataset.handoffWaiting=String(handoffWaiting);indicator.dataset.coolingDown=String(coolingDown);indicator.dataset.voiceInputListening=String(voiceInputListening);indicator.dataset.voiceOutputSpeaking=String(voiceOutputSpeaking);indicator.dataset.networkRetry=String(networkStreak);};
 const stop=()=>{clear('restart');const active=recognition;recognition=null;listening=false;render();try{active?.stop?.();}catch{}};
 const disable=(code:string)=>{enabled=false;clear('restart');clear('handoff');clear('session');clear('cooldown');stop();render();announce(terminalRecognitionMessage(code));};
 const handleError=(value:unknown)=>{const result=classifyRecognitionError(value);if(result.kind==='aborted')return;if(result.kind==='idle'){restartTimer=0;return;}if(result.kind==='network'){networkStreak++;if(networkStreak>HANDS_FREE_RETRY_DELAYS.length){disable('network');return;}restartTimer=rootRef.setTimeout(()=>{restartTimer=0;startRecognition();},networkRetryDelay(networkStreak));render();return;}disable(result.code);};
 const scheduleSession=()=>{clear('session');sessionTimer=rootRef.setTimeout(()=>{enabled=false;stop();render();announce('Eller serbest dinleme 30 dakikalık güvenlik süresi sonunda kapatıldı.');},HANDS_FREE_LIMITS.session);};
 const finishHandoff=()=>{clear('handoff');if(!enabled||destroyed||voiceInputListening)return;handoffWaiting=false;render();startRecognition();};
 const armHandoff=()=>{clear('handoff');handoffWaiting=true;render();handoffTimer=rootRef.setTimeout(()=>{handoffTimer=0;handoffWaiting=false;if(enabled&&!voiceInputListening)startRecognition();},HANDS_FREE_LIMITS.handoffTimeout);};
 const startRecognition=()=>{if(destroyed||!enabled||!Recognition||recognition||handoffWaiting||coolingDown||voiceInputListening||voiceOutputSpeaking||documentRef.hidden||input.disabled)return;const current=new Recognition();recognition=current;current.lang=documentRef.documentElement.lang||rootRef.navigator.language||'tr-TR';current.continuous=true;current.interimResults=false;current.maxAlternatives=1;current.onstart=()=>{listening=true;networkStreak=0;render();};current.onresult=(event:any)=>{const transcript=readRecognitionText(event);if(!containsWakePhrase(transcript))return;armHandoff();try{rootRef.dispatchEvent(new CustomEvent(HANDS_FREE_EVENTS.input,{detail:{transcript,explicitWake:true}}));}catch{}};current.onerror=(event:any)=>handleError(event?.error);current.onend=()=>{recognition=null;listening=false;render();if(enabled&&!handoffWaiting&&!coolingDown&&!voiceInputListening&&!voiceOutputSpeaking&&!documentRef.hidden)restartTimer=rootRef.setTimeout(()=>{restartTimer=0;startRecognition();},HANDS_FREE_LIMITS.restartDelay);};try{current.start();}catch{recognition=null;listening=false;render();scheduleSession();}};
 const setEnabled=(value:boolean)=>{if(!Recognition){enabled=false;render();announce('Bu tarayıcı eller serbest konuşma tanımayı desteklemiyor.');return;}enabled=Boolean(value);if(enabled){networkStreak=0;scheduleSession();startRecognition();announce('Eller serbest açıldı. “Hafize” dediğinde dinleme başlatılabilir.');}else{clear('session');clear('handoff');clear('cooldown');stop();announce('Eller serbest kapatıldı.');}render();};
 const toggleClick=(event:Event)=>{event.preventDefault();setEnabled(!enabled);};const visibility=()=>{if(documentRef.hidden&&enabled)stop();if(!documentRef.hidden&&enabled&&!recognition&&!handoffWaiting&&!coolingDown&&!voiceInputListening&&!voiceOutputSpeaking)startRecognition();};
 on(toggle,'click',toggleClick,undefined,disposer);on(documentRef,'visibilitychange',visibility,undefined,disposer);
 on(rootRef,HANDS_FREE_EVENTS.revoke,(()=>setEnabled(false))as EventListener,undefined,disposer);on(rootRef,HANDS_FREE_EVENTS.input,(()=>{voiceInputListening=true;armHandoff();render();}),undefined,disposer);on(rootRef,HANDS_FREE_EVENTS.output,((event:Event)=>{voiceOutputSpeaking=Boolean((event as CustomEvent<{speaking?:boolean}>).detail?.speaking);if(voiceOutputSpeaking){clear('restart');stop();}else if(enabled) {coolingDown=true;render();cooldownTimer=rootRef.setTimeout(()=>{cooldownTimer=0;coolingDown=false;startRecognition();},HANDS_FREE_LIMITS.cooldown);}})as EventListener,undefined,disposer);
 const observer=new MutationObserver(()=>{if(input.disabled&&enabled)stop();render();});observer.observe(input,{attributes:true,attributeFilter:['disabled']});disposer.add(()=>observer.disconnect());render();return Object.freeze({isSupported:Boolean(Recognition),isEnabled:()=>enabled,isListening:()=>listening,setEnabled,destroy:()=>{destroyed=true;clear('restart');clear('handoff');clear('session');clear('cooldown');stop();disposer.flush();}});
}

const start=()=>mountHandsFree(document,window);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
