export type MemoryKind = 'fact' | 'preference' | 'instruction' | 'project' | 'note';
export interface MemoryRecord { readonly id: string; readonly kind: MemoryKind; readonly text: string; readonly tags: readonly string[]; readonly createdAt: string; readonly updatedAt: string; readonly source: 'user' | 'assistant' | 'import'; readonly pinned: boolean; }
export interface MemoryQuery { readonly query: string; readonly kinds: readonly MemoryKind[]; readonly pinnedOnly: boolean; }

export const MEMORY_LIMITS = Object.freeze({ maxRecords: 200, maxText: 2_000, maxTag: 32, maxTags: 8, maxQuery: 120 });
const KINDS: readonly MemoryKind[] = Object.freeze(['fact', 'preference', 'instruction', 'project', 'note']);
const normalize = (value: unknown, max: number): string => typeof value === 'string' ? value.replace(/\0/g, '').trim().slice(0, max) : '';
export const normalizeMemoryKind = (value: unknown): MemoryKind => KINDS.includes(value as MemoryKind) ? value as MemoryKind : 'note';
export const normalizeMemoryTags = (value: unknown): string[] => Array.isArray(value) ? [...new Set(value.map((tag) => normalize(tag, MEMORY_LIMITS.maxTag)).filter(Boolean))].slice(0, MEMORY_LIMITS.maxTags) : [];

export function normalizeMemory(value: unknown, fallbackId = 'memory'): MemoryRecord | null { if (!value || typeof value !== 'object') return null; const item = value as Record<string, unknown>; const text = normalize(item.text, MEMORY_LIMITS.maxText); if (!text) return null; const created = typeof item.createdAt === 'string' && Number.isFinite(Date.parse(item.createdAt)) ? new Date(item.createdAt).toISOString() : new Date().toISOString(); const updated = typeof item.updatedAt === 'string' && Number.isFinite(Date.parse(item.updatedAt)) ? new Date(item.updatedAt).toISOString() : created; const source = item.source === 'assistant' || item.source === 'import' ? item.source : 'user'; return Object.freeze({ id: normalize(item.id, 120) || fallbackId, kind: normalizeMemoryKind(item.kind), text, tags: normalizeMemoryTags(item.tags), createdAt: created, updatedAt: updated, source, pinned: item.pinned === true }); }
export function normalizeMemoryList(value: unknown): MemoryRecord[] { if (!Array.isArray(value)) return []; const seen = new Set<string>(); const output: MemoryRecord[] = []; value.forEach((item, index) => { const memory = normalizeMemory(item, `memory-${index}`); if (!memory || seen.has(memory.id)) return; seen.add(memory.id); output.push(memory); }); return output.slice(0, MEMORY_LIMITS.maxRecords); }
export function memoryMatches(memory: MemoryRecord, query: MemoryQuery): boolean { if (query.pinnedOnly && !memory.pinned) return false; if (query.kinds.length && !query.kinds.includes(memory.kind)) return false; const wanted = normalize(query.query, MEMORY_LIMITS.maxQuery).toLocaleLowerCase('tr-TR'); if (!wanted) return true; return [memory.text, ...memory.tags, memory.kind].join('\n').toLocaleLowerCase('tr-TR').includes(wanted); }
export function searchMemories(memories: readonly MemoryRecord[], query: MemoryQuery): MemoryRecord[] { return memories.filter((memory) => memoryMatches(memory, query)).sort((a, b) => Number(b.pinned) - Number(a.pinned) || b.updatedAt.localeCompare(a.updatedAt)); }
export function upsertMemory(memories: readonly MemoryRecord[], value: MemoryRecord): MemoryRecord[] { const next = normalizeMemory(value, value.id); if (!next) throw new Error('INVALID_MEMORY'); return normalizeMemoryList([next, ...memories.filter((memory) => memory.id !== next.id)]); }
export function removeMemory(memories: readonly MemoryRecord[], id: string): MemoryRecord[] { return memories.filter((memory) => memory.id !== id); }
export const HafizeMemoryModel = Object.freeze({ normalizeMemoryKind, normalizeMemoryTags, normalizeMemory, normalizeMemoryList, memoryMatches, searchMemories, upsertMemory, removeMemory, MEMORY_LIMITS });
