import { Disposer, on, query, safeJsonParse, boundedText, text } from './browser-platform.ts';

export const MESSAGE_WORKSPACE_KEY = 'hafize.message-workspace.v1';
export const MESSAGE_WORKSPACE_STATE_KEY = `${MESSAGE_WORKSPACE_KEY}.state`;
export const MESSAGE_WORKSPACE_LIMITS = Object.freeze({ records: 240, note: 600, tag: 24, tags: 8, query: 120, export: 100 });
export const MESSAGE_WORKSPACE_FILTERS = Object.freeze(['all', 'saved', 'feedback', 'notes', 'user', 'assistant', 'tag'] as const);
export const MESSAGE_WORKSPACE_SORTS = Object.freeze(['newest', 'oldest', 'feedback', 'notes'] as const);
export type MessageFeedback = '' | 'up' | 'down';
export type MessageFilter = (typeof MESSAGE_WORKSPACE_FILTERS)[number];
export type MessageSort = (typeof MESSAGE_WORKSPACE_SORTS)[number];
export type MessageRecord = { id: string; conversationId: string; messageId: string; saved: boolean; feedback: MessageFeedback; note: string; tags: string[]; createdAt: string; updatedAt: string };
export type MessageWorkspaceState = { query: string; filter: MessageFilter; sort: MessageSort; selected: string[] };
export type MessageView = { record: MessageRecord; role: 'user' | 'assistant'; content: string };

export const DEFAULT_MESSAGE_STATE: MessageWorkspaceState = Object.freeze({ query: '', filter: 'all', sort: 'newest', selected: [] });

export function cleanText(value: unknown, max = MESSAGE_WORKSPACE_LIMITS.note): string { return typeof value === 'string' ? value.replace(/\0/g, '').replace(/\r\n?/g, '\n').trim().slice(0, max) : ''; }
export function cleanTag(value: unknown): string { return cleanText(value, MESSAGE_WORKSPACE_LIMITS.tag).replace(/^#+/, ''); }
export function normalizeFeedback(value: unknown): MessageFeedback { return value === 'up' || value === 'down' ? value : ''; }
export function normalizeRecord(value: unknown): MessageRecord | null {
  if (!value || typeof value !== 'object') return null;
  const item = value as Record<string, unknown>;
  if (typeof item.conversationId !== 'string' || !item.conversationId || typeof item.messageId !== 'string' || !item.messageId) return null;
  const now = new Date().toISOString(); const tags = Array.isArray(item.tags) ? [...new Set(item.tags.map(cleanTag).filter(Boolean))].slice(0, MESSAGE_WORKSPACE_LIMITS.tags) : [];
  const date = (input: unknown) => { const parsed = new Date(String(input || '')); return Number.isFinite(parsed.getTime()) ? parsed.toISOString() : now; };
  return { id: typeof item.id === 'string' && item.id ? item.id.slice(0, 120) : `${item.conversationId}:${item.messageId}`, conversationId: item.conversationId.slice(0, 120), messageId: item.messageId.slice(0, 120), saved: item.saved === true, feedback: normalizeFeedback(item.feedback), note: cleanText(item.note), tags, createdAt: date(item.createdAt), updatedAt: date(item.updatedAt) };
}
export function normalizeRecords(value: unknown): MessageRecord[] { if (!Array.isArray(value)) return []; const seen = new Set<string>(); const result: MessageRecord[] = []; for (const raw of value.slice(0, MESSAGE_WORKSPACE_LIMITS.records * 2)) { const item = normalizeRecord(raw); if (!item || seen.has(item.id)) continue; seen.add(item.id); if (!(item.saved || item.feedback || item.note || item.tags.length)) continue; result.push(item); if (result.length >= MESSAGE_WORKSPACE_LIMITS.records) break; } return result; }
export function normalizeState(value: unknown): MessageWorkspaceState { const item = value && typeof value === 'object' ? value as Record<string, unknown> : {}; const filter = MESSAGE_WORKSPACE_FILTERS.includes(String(item.filter) as MessageFilter) ? String(item.filter) as MessageFilter : 'all'; const sort = MESSAGE_WORKSPACE_SORTS.includes(String(item.sort) as MessageSort) ? String(item.sort) as MessageSort : 'newest'; return { query: cleanText(item.query, MESSAGE_WORKSPACE_LIMITS.query).toLocaleLowerCase('tr-TR'), filter, sort, selected: Array.isArray(item.selected) ? item.selected.filter((id): id is string => typeof id === 'string').slice(0, MESSAGE_WORKSPACE_LIMITS.export) : [] }; }
export function readRecords(storage: Storage = localStorage): MessageRecord[] { try { return normalizeRecords(safeJsonParse<unknown>(storage.getItem(MESSAGE_WORKSPACE_KEY), [])); } catch { return []; } }
export function readState(storage: Storage = localStorage): MessageWorkspaceState { try { return normalizeState(safeJsonParse<unknown>(storage.getItem(MESSAGE_WORKSPACE_STATE_KEY), DEFAULT_MESSAGE_STATE)); } catch { return { ...DEFAULT_MESSAGE_STATE, selected: [] }; } }
export function saveRecords(records: MessageRecord[], storage: Storage = localStorage): boolean { try { storage.setItem(MESSAGE_WORKSPACE_KEY, JSON.stringify(normalizeRecords(records))); return true; } catch { return false; } }
export function saveState(state: MessageWorkspaceState, storage: Storage = localStorage): boolean { try { storage.setItem(MESSAGE_WORKSPACE_STATE_KEY, JSON.stringify(normalizeState(state))); return true; } catch { return false; } }
export function recordHasData(record: MessageRecord): boolean { return record.saved || Boolean(record.feedback) || Boolean(record.note) || record.tags.length > 0; }
export function messageMatches(view: MessageView, state: MessageWorkspaceState): boolean { const record = view.record; if (state.filter === 'saved' && !record.saved) return false; if (state.filter === 'feedback' && !record.feedback) return false; if (state.filter === 'notes' && !record.note) return false; if (state.filter === 'user' && view.role !== 'user') return false; if (state.filter === 'assistant' && view.role !== 'assistant') return false; if (state.filter === 'tag' && !record.tags.length) return false; if (!state.query) return true; const haystack = cleanText(`${view.content} ${record.note} ${record.tags.join(' ')}`, 20_000).toLocaleLowerCase('tr-TR'); return haystack.includes(state.query); }
export function sortViews(views: MessageView[], sort: MessageSort): MessageView[] { const result = views.slice(); if (sort === 'feedback') return result.sort((a, b) => Number(Boolean(b.record.feedback)) - Number(Boolean(a.record.feedback)) || b.record.updatedAt.localeCompare(a.record.updatedAt)); if (sort === 'notes') return result.sort((a, b) => Number(Boolean(b.record.note)) - Number(Boolean(a.record.note)) || b.record.updatedAt.localeCompare(a.record.updatedAt)); return result.sort((a, b) => sort === 'oldest' ? a.record.updatedAt.localeCompare(b.record.updatedAt) : b.record.updatedAt.localeCompare(a.record.updatedAt)); }
export function filterViews(views: MessageView[], state: MessageWorkspaceState): MessageView[] { return sortViews(views.filter((view) => messageMatches(view, state)), state.sort); }
export function mergeRecord(existing: MessageRecord | null, patch: Partial<MessageRecord>): MessageRecord { const base = existing || { id: `${patch.conversationId || 'conversation'}:${patch.messageId || 'message'}`, conversationId: String(patch.conversationId || ''), messageId: String(patch.messageId || ''), saved: false, feedback: '', note: '', tags: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; const normalized = normalizeRecord({ ...base, ...patch, updatedAt: new Date().toISOString() }); if (!normalized) throw new Error('MESSAGE_RECORD_INVALID'); return normalized; }
export function removeEmptyRecords(records: MessageRecord[]): MessageRecord[] { return normalizeRecords(records.filter(recordHasData)); }
export function collectMessageTags(records: MessageRecord[]): Array<{ label: string; count: number }> { const map = new Map<string, { label: string; count: number }>(); for (const record of records) for (const raw of record.tags) { const label = cleanTag(raw); const key = label.toLocaleLowerCase('tr-TR'); if (!key) continue; const entry = map.get(key) || { label, count: 0 }; entry.count += 1; map.set(key, entry); } return [...map.values()].sort((a, b) => b.count - a.count || a.label.localeCompare(b.label, 'tr-TR')); }

export function exportRecords(records: MessageRecord[]): string { return JSON.stringify({ version: 1, source: 'hafize-message-workspace', exportedAt: new Date().toISOString(), records: normalizeRecords(records).slice(0, MESSAGE_WORKSPACE_LIMITS.export) }, null, 2); }

export function mountMessageWorkspace(documentRef: Document = document, rootRef: Window = window): Readonly<{ getRecords: () => MessageRecord[]; getState: () => MessageWorkspaceState; setState: (patch: Partial<MessageWorkspaceState>) => void; refresh: () => void; destroy: () => void }> | null {
  const messages = query<HTMLElement>(documentRef, '#messages'); const rail = query<HTMLElement>(documentRef, '.utility-rail'); if (!messages || !rail || documentRef.getElementById('typedMessageWorkspace')) return null;
  const disposer = new Disposer(); let records = readRecords(rootRef.localStorage); let state = readState(rootRef.localStorage); const panel = text<HTMLElement>(documentRef, 'section', '', 'message-workspace'); panel.id = 'typedMessageWorkspace'; panel.setAttribute('aria-labelledby', 'typedMessageWorkspaceTitle'); const title = text<HTMLHeadingElement>(documentRef, 'h2', 'Mesaj çalışma alanı'); title.id = 'typedMessageWorkspaceTitle'; const search = documentRef.createElement('input'); search.type='search'; search.maxLength=MESSAGE_WORKSPACE_LIMITS.query; search.placeholder='Mesaj, not veya etiket…'; search.setAttribute('aria-label','Mesaj çalışma alanında ara'); const filter=documentRef.createElement('select'); filter.setAttribute('aria-label','Mesaj filtresi'); MESSAGE_WORKSPACE_FILTERS.forEach((value)=>filter.append(new Option(value==='all'?'Tümü':value,value))); const sort=documentRef.createElement('select'); sort.setAttribute('aria-label','Mesaj sıralaması'); MESSAGE_WORKSPACE_SORTS.forEach((value)=>sort.append(new Option(value,value))); const status=text<HTMLElement>(documentRef,'span','','message-workspace-status'); panel.append(title,search,filter,sort,status); rail.append(panel);
  const refresh=()=>{ records=readRecords(rootRef.localStorage); state=readState(rootRef.localStorage); search.value=state.query; filter.value=state.filter; sort.value=state.sort; status.textContent=`${records.length} kayıt · ${state.selected.length} seçili`; };
  const setState=(patch:Partial<MessageWorkspaceState>)=>{ state=normalizeState({...state,...patch}); saveState(state,rootRef.localStorage); refresh(); };
  on(search,'input',()=>setState({query:search.value}),undefined,disposer); on(filter,'change',()=>setState({filter:filter.value as MessageFilter}),undefined,disposer); on(sort,'change',()=>setState({sort:sort.value as MessageSort}),undefined,disposer); on(rootRef,'storage',((event:Event)=>{if((event as StorageEvent).key===MESSAGE_WORKSPACE_KEY || (event as StorageEvent).key===MESSAGE_WORKSPACE_STATE_KEY)refresh();})as EventListener,undefined,disposer); refresh();
  return Object.freeze({getRecords:()=>records.slice(),getState:()=>({...state,selected:[...state.selected]}),setState,refresh,destroy:()=>{disposer.flush();panel.remove();}});
}

const start=()=>mountMessageWorkspace(document,window);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
