export type NetworkState = 'online' | 'offline' | 'degraded' | 'unknown';
export interface NetworkSnapshot { readonly state: NetworkState; readonly online: boolean; readonly effectiveType?: string; readonly rttMs?: number; readonly downlinkMbps?: number; readonly saveData: boolean; readonly checkedAt: string; }
export interface NetworkHealthController { readonly snapshot: () => NetworkSnapshot; readonly refresh: () => NetworkSnapshot; readonly subscribe: (listener: (snapshot: NetworkSnapshot) => void) => () => void; readonly destroy: () => void; }
interface ConnectionLike { readonly effectiveType?: string; readonly rtt?: number; readonly downlink?: number; readonly saveData?: boolean; }
interface NetworkNavigator extends Navigator { readonly connection?: ConnectionLike; }

const degradedTypes = new Set(['slow-2g', '2g']);
export function classifyNetwork(online: boolean, connection?: ConnectionLike): NetworkState { if (!online) return 'offline'; if (connection?.effectiveType && degradedTypes.has(connection.effectiveType)) return 'degraded'; return 'online'; }
export function readNetworkSnapshot(navigatorRef: NetworkNavigator = navigator): NetworkSnapshot { const connection = navigatorRef.connection; const online = navigatorRef.onLine !== false; const snapshot: NetworkSnapshot = { state: classifyNetwork(online, connection), online, ...(connection?.effectiveType ? { effectiveType: connection.effectiveType } : {}), ...(Number.isFinite(connection?.rtt) ? { rttMs: Number(connection?.rtt) } : {}), ...(Number.isFinite(connection?.downlink) ? { downlinkMbps: Number(connection?.downlink) } : {}), saveData: connection?.saveData === true, checkedAt: new Date().toISOString() }; return Object.freeze(snapshot); }
export function installNetworkHealth(windowRef: Window = window): NetworkHealthController { let current = readNetworkSnapshot(windowRef.navigator as NetworkNavigator); const listeners = new Set<(snapshot: NetworkSnapshot) => void>(); const emit = (): void => { current = readNetworkSnapshot(windowRef.navigator as NetworkNavigator); for (const listener of listeners) { try { listener(current); } catch {} } }; const onChange = (): void => emit(); windowRef.addEventListener('online', onChange); windowRef.addEventListener('offline', onChange); const connection = (windowRef.navigator as NetworkNavigator).connection; if (connection && 'addEventListener' in connection) (connection as unknown as EventTarget).addEventListener('change', onChange); return Object.freeze({ snapshot: () => current, refresh: () => { emit(); return current; }, subscribe: (listener) => { listeners.add(listener); return () => listeners.delete(listener); }, destroy: () => { windowRef.removeEventListener('online', onChange); windowRef.removeEventListener('offline', onChange); if (connection && 'removeEventListener' in connection) (connection as unknown as EventTarget).removeEventListener('change', onChange); listeners.clear(); } }); }
export function shouldPreferLocalQueue(snapshot: NetworkSnapshot): boolean { return snapshot.state === 'offline' || (snapshot.state === 'degraded' && (snapshot.rttMs ?? 0) >= 1500); }
export const HafizeNetworkHealth = Object.freeze({ classifyNetwork, readNetworkSnapshot, installNetworkHealth, shouldPreferLocalQueue });
