import { Disposer, on, query, safeJsonParse, boundedText, text } from './browser-platform.ts';

export const SCHEDULE_LIMITS = Object.freeze({ task: 20_000, list: 128, attempts: 5, refreshMs: 30_000 });
export const SCHEDULE_API_PATH = '/api/schedules';
export type ScheduleStatus = 'scheduled' | 'running' | 'completed' | 'failed' | 'cancelled';
export type ScheduleEntry = { scheduleId?: unknown; status?: unknown; runAt?: unknown; agentId?: unknown; task?: unknown; attempts?: unknown; maxAttempts?: unknown; lastError?: unknown; traceId?: unknown };

export function normalizeStatus(value: unknown): ScheduleStatus | 'unknown' { return ['scheduled', 'running', 'completed', 'failed', 'cancelled'].includes(String(value)) ? value as ScheduleStatus : 'unknown'; }
export function statusText(value: unknown): string { return ({ scheduled: 'Planlandı', running: 'Çalışıyor', completed: 'Tamamlandı', failed: 'Başarısız', cancelled: 'İptal edildi' } as Record<string, string>)[normalizeStatus(value)] || 'Bilinmiyor'; }
export function isoFromLocal(value: string): string { const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : date.toISOString(); }
export function localDateTimeValue(offsetMinutes = 5, now = new Date()): string { const date = new Date(now.getTime() + offsetMinutes * 60_000); const pad = (value: number) => String(value).padStart(2, '0'); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`; }
export function formatScheduleDate(value: unknown): string { const timestamp = Date.parse(typeof value === 'string' ? value : ''); return Number.isFinite(timestamp) ? new Intl.DateTimeFormat('tr-TR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(timestamp)) : 'Tarih bilinmiyor'; }

function button(documentRef: Document, label: string, action: string, className = 'mini-btn'): HTMLButtonElement { const node = text<HTMLButtonElement>(documentRef, 'button', label, className); node.type = 'button'; node.dataset.taskAction = action; return node; }
function safeJsonPayload(value: unknown): Record<string, unknown> { return value && typeof value === 'object' ? value as Record<string, unknown> : {}; }

export function mountScheduledTasks(documentRef: Document = document, rootRef: Window = window): Readonly<{ open: () => void; close: () => void; refresh: () => Promise<void>; destroy: () => void }> | null {
  const nav = [...documentRef.querySelectorAll<HTMLButtonElement>('.nav-item')].find((node) => node.textContent?.includes('Görevler')); if (!nav) return null;
  const disposer = new Disposer(); let panel: HTMLElement | null = null; let controller: AbortController | null = null; let refreshTimer = 0; let lastFocus: Element | null = null; let selectedStatus = 'all';
  const make = (tag: string, value = '', className = '') => text<HTMLElement>(documentRef, tag, value, className);
  const status = (message: string, tone = '') => { const target = panel?.querySelector<HTMLElement>('.scheduled-tasks-status'); if (target) { target.textContent = boundedText(message, 220); target.dataset.tone = tone; } };
  const request = async (path = SCHEDULE_API_PATH, options: RequestInit = {}) => { controller?.abort(); controller = new AbortController(); const headers = new Headers(options.headers || {}); headers.set('Accept', 'application/json'); if (options.body) headers.set('Content-Type', 'application/json'); const response = await rootRef.fetch(path, { ...options, credentials: 'same-origin', headers, signal: controller.signal }); const payload = safeJsonParse<unknown>(await response.text(), null); if (!response.ok) { const error = new Error(typeof payload === 'object' && payload && ('code' in payload || 'error' in payload) ? String((payload as Record<string, unknown>).code || (payload as Record<string, unknown>).error) : `HTTP_${response.status}`); Object.assign(error, { status: response.status, payload }); throw error; } return safeJsonPayload(payload); };
  const agentOptions = () => { const select = query<HTMLSelectElement>(documentRef, '#agentSelect'); return select ? [...select.options].filter((option) => option.value).map((option) => ({ id: option.value, label: option.textContent?.trim() || option.value })) : []; };
  const build = () => {
    panel = make('section', '', 'scheduled-tasks-overlay'); panel.id = 'scheduledTasksWorkspace'; panel.hidden = true; panel.setAttribute('role', 'dialog'); panel.setAttribute('aria-modal', 'true'); panel.setAttribute('aria-labelledby', 'scheduledTasksTitle');
    const shell = make('div', '', 'scheduled-tasks-shell'); const head = make('div', '', 'scheduled-tasks-head'); const title = make('strong', 'Zamanlanmış görevler', 'scheduled-tasks-title'); title.id = 'scheduledTasksTitle'; head.append(title, button(documentRef, 'Yenile', 'refresh'), button(documentRef, 'Kapat', 'close')); shell.append(head);
    const form = documentRef.createElement('form'); form.className = 'scheduled-tasks-create'; form.noValidate = true; form.append(make('div', 'Yeni görev planla', 'scheduled-tasks-section-title'));
    const agentLabel = make('label', 'Ajan'); const agent = documentRef.createElement('select'); agent.id = 'scheduledTaskAgent'; agent.required = true; agent.setAttribute('aria-label', 'Zamanlanmış görev ajanı'); agentOptions().forEach((item) => { const option = text<HTMLOptionElement>(documentRef, 'option', item.label); option.value = item.id; agent.append(option); }); if (!agent.options.length) { const option = text<HTMLOptionElement>(documentRef, 'option', 'Ajanlar yükleniyor'); option.value = ''; agent.append(option); agent.disabled = true; } agentLabel.append(agent);
    const taskLabel = make('label', 'Görev metni'); const task = documentRef.createElement('textarea'); task.rows = 5; task.maxLength = SCHEDULE_LIMITS.task; task.required = true; task.placeholder = 'Örn. Bugünkü önemli gelişmeleri özetle ve takip edilmesi gereken noktaları çıkar.'; task.setAttribute('aria-label', 'Zamanlanacak görev metni'); taskLabel.append(task);
    const whenLabel = make('label', 'Çalıştırma zamanı'); const when = documentRef.createElement('input'); when.type = 'datetime-local'; when.required = true; when.value = localDateTimeValue(); when.min = localDateTimeValue(); whenLabel.append(when);
    const attemptsLabel = make('label', 'Maksimum deneme'); const attempts = documentRef.createElement('select'); attempts.setAttribute('aria-label', 'Maksimum deneme sayısı'); for (let i = 1; i <= SCHEDULE_LIMITS.attempts; i++) { const option = text<HTMLOptionElement>(documentRef, 'option', String(i)); option.value = String(i); attempts.append(option); } attemptsLabel.append(attempts);
    const grid = make('div', '', 'scheduled-tasks-form-grid'); grid.append(agentLabel, whenLabel, attemptsLabel); const submit = button(documentRef, 'Görevi planla', 'create', 'soft-btn'); submit.classList.add('primary'); form.append(taskLabel, grid, submit);
    const section = make('section', '', 'scheduled-tasks-list-section'); section.setAttribute('aria-label', 'Planlanmış görevler listesi'); section.append(make('div', 'Planlanan görevler', 'scheduled-tasks-section-title')); const filter = make('div', '', 'scheduled-tasks-filter'); const select = documentRef.createElement('select'); select.setAttribute('aria-label', 'Görev durumuna göre filtrele'); [['all','Tümü'],['scheduled','Planlandı'],['running','Çalışıyor'],['completed','Tamamlandı'],['failed','Başarısız'],['cancelled','İptal edildi']].forEach(([value, label]) => { const option = text<HTMLOptionElement>(documentRef, 'option', label); option.value = value; select.append(option); }); const info = make('span', '', 'scheduled-tasks-filter-info'); filter.append(select, info); const list = make('div', '', 'scheduled-tasks-list'); list.setAttribute('role', 'list'); section.append(filter, list); const statusNode = make('div', '', 'scheduled-tasks-status'); statusNode.setAttribute('role', 'status'); statusNode.setAttribute('aria-live', 'polite'); shell.append(form, statusNode, section); panel.append(shell); documentRef.body.append(panel);
    on(form, 'submit', (event: Event) => { event.preventDefault(); void createTask(agent.value, task.value, when.value, Number(attempts.value), submit); }, undefined, disposer);
    on(select, 'change', () => { selectedStatus = select.value; applyFilter(list, info); }, undefined, disposer); on(panel, 'click', ((event: Event) => { const target = (event.target as Element | null)?.closest<HTMLButtonElement>('[data-task-action]'); if (!target) return; const action = target.dataset.taskAction; if (action === 'close') close(); else if (action === 'refresh') void refresh(); else if (action === 'cancel') void cancelTask(target.closest<HTMLElement>('.scheduled-task-row')?.dataset.scheduleId || ''); else if (action === 'trace') status(`Trace ID: ${target.title}`,'info'); }) as EventListener, undefined, disposer); on(panel, 'keydown', ((event: Event) => { if ((event as KeyboardEvent).key === 'Escape') { event.preventDefault(); close(); } }) as EventListener, undefined, disposer);
  };
  const renderRow = (entry: ScheduleEntry) => { const item = make('article', '', 'scheduled-task-row'); const id = boundedText(entry.scheduleId, 120); const state = normalizeStatus(entry.status); item.dataset.scheduleId = id; item.dataset.status = state; item.dataset.runAt = boundedText(entry.runAt, 40); item.setAttribute('role','listitem'); const head = make('div','', 'scheduled-task-row-head'); head.append(make('strong', boundedText(entry.task, 120))); head.append(make('span', statusText(state), `scheduled-task-status status-${state}`)); const meta = make('div', `${formatScheduleDate(entry.runAt)} · ${boundedText(entry.agentId,80)} · deneme ${Number(entry.attempts) || 0}/${Number(entry.maxAttempts) || 0}`, 'scheduled-task-meta'); const detail = make('p', entry.lastError ? `Son hata: ${boundedText(entry.lastError,120)}` : state === 'completed' ? 'Başarıyla tamamlandı.' : ''); const actions = make('div','', 'scheduled-task-actions'); if (state === 'scheduled') actions.append(button(documentRef,'İptal et','cancel')); const trace = button(documentRef,'Trace ID','trace'); trace.title = boundedText(entry.traceId,128); trace.setAttribute('aria-label', `Trace ID: ${boundedText(entry.traceId,40)}`); actions.append(trace); item.append(head, meta, detail, actions); return item; };
  const applyFilter = (list: HTMLElement, info: HTMLElement) => { let visible = 0; [...list.children].forEach((node) => { const row = node as HTMLElement; if (!row.classList.contains('scheduled-task-row')) return; const show = selectedStatus === 'all' || row.dataset.status === selectedStatus; row.hidden = !show; if (show) visible++; }); info.textContent = `${visible} görev gösteriliyor.`; };
  const createTask = async (agentId: string, taskText: string, whenValue: string, maxAttempts: number, submit: HTMLButtonElement) => { const task = taskText.trim(); const runAt = isoFromLocal(whenValue); if (!agentId) return status('Geçerli bir ajan seçmelisin.','error'); if (!task) return status('Görev metni boş olamaz.','error'); if (!runAt || Date.parse(runAt) <= Date.now()) return status('Çalıştırma zamanı gelecekte olmalı.','error'); submit.disabled = true; try { await request(SCHEDULE_API_PATH,{method:'POST',body:JSON.stringify({agentId,task,runAt,maxAttempts})}); status('Görev planlandı.','success'); const textarea = panel?.querySelector<HTMLTextAreaElement>('#scheduledTasksWorkspace textarea'); if (textarea) textarea.value=''; const whenInput = panel?.querySelector<HTMLInputElement>('input[type="datetime-local"]'); if (whenInput) whenInput.value=localDateTimeValue(); await refresh(); } catch (error) { status((error as { status?: number; message?: string }).status===401?'Oturum açılması gerekiyor.':(error as Error).message==='SCHEDULE_CAPACITY_REACHED'?'Görev kapasitesi dolu.':'Görev planlanamadı.','error'); } finally { submit.disabled=false; } };
  const refresh = async () => { const list = panel?.querySelector<HTMLElement>('.scheduled-tasks-list'); const info = panel?.querySelector<HTMLElement>('.scheduled-tasks-filter-info'); if (!list || !info) return; list.replaceChildren(make('div','Görevler yükleniyor…','scheduled-tasks-empty')); try { const payload = await request(); const raw = Array.isArray(payload.schedules) ? payload.schedules.slice(0,SCHEDULE_LIMITS.list) : []; raw.sort((a,b)=>String(a.runAt).localeCompare(String(b.runAt))||String(a.scheduleId).localeCompare(String(b.scheduleId))); list.replaceChildren(); if (!raw.length) list.append(make('div','Henüz planlanmış görev yok.','scheduled-tasks-empty')); else raw.forEach((entry)=>list.append(renderRow(entry as ScheduleEntry))); applyFilter(list,info); } catch (error) { list.replaceChildren(make('div',(error as { status?: number }).status===401?'Görevleri görmek için oturum açmalısın.':'Görev listesi yüklenemedi.','scheduled-tasks-empty')); status((error as { status?: number }).status===401?'Kimlik doğrulama gerekli.':'Görev servisine ulaşılamadı.','error'); } };
  const cancelTask = async (id: string) => { if (!id || !rootRef.confirm('Bu planlanmış görev iptal edilsin mi?')) return; try { await request(`${SCHEDULE_API_PATH}/${encodeURIComponent(id)}`,{method:'DELETE'}); status('Görev iptal edildi.','success'); await refresh(); } catch { status('Görev iptal edilemedi.','error'); await refresh(); } };
  const open = () => { if (!panel) build(); if (!panel) return; lastFocus = documentRef.activeElement; panel.hidden=false; selectedStatus='all'; const filter=panel.querySelector<HTMLSelectElement>('.scheduled-tasks-filter select'); if (filter) filter.value='all'; void refresh(); rootRef.clearInterval(refreshTimer); refreshTimer=rootRef.setInterval(()=>void refresh(),SCHEDULE_LIMITS.refreshMs); panel.querySelector<HTMLButtonElement>('[data-task-action="close"]')?.focus(); };
  const close = () => { if (!panel) return; panel.hidden=true; rootRef.clearInterval(refreshTimer); refreshTimer=0; controller?.abort(); lastFocus instanceof HTMLElement && lastFocus.focus(); lastFocus=null; };
  on(nav,'click',(event: Event)=>{event.preventDefault();open();},undefined,disposer); nav.disabled=false; nav.setAttribute('aria-controls','scheduledTasksWorkspace');
  return Object.freeze({ open, close, refresh, destroy: () => { close(); disposer.flush(); panel?.remove(); } });
}

const start=()=>mountScheduledTasks(document,window); if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',start,{once:true}); else start();
