interface HafizeAttachment { readonly name: string; readonly size: number; readonly lastModified: number; readonly block: string; }
interface ComposerForm extends HTMLFormElement { _hafizeAttachments?: HafizeAttachment[]; }
interface ComposerRoot extends Window { readonly hafize?: unknown; }
export const COMPOSER_LIMITS = Object.freeze({ maxFileBytes: 384 * 1024, maxAttachments: 3, maxAttachmentText: 9000 });
const ACCEPTED = /\.(?:txt|md|markdown|json|csv|tsv|html?|css|js|mjs|cjs|jsx|tsx|py|java|c|h|cpp|hpp|xml|yaml|yml|toml|ini|log)$/i;

export function acceptedFile(file: File | null | undefined): boolean { return Boolean(file && Number.isFinite(file.size) && file.size > 0 && file.size <= COMPOSER_LIMITS.maxFileBytes && (file.type.startsWith('text/') || file.type === 'application/json' || ACCEPTED.test(file.name))); }
export function composeAttachment(file: Pick<File, 'name'>, source: string): string { const clipped = source.replace(/\r\n/g, '\n').slice(0, COMPOSER_LIMITS.maxAttachmentText); const notice = source.length > COMPOSER_LIMITS.maxAttachmentText ? `\n[Dosya içeriği ${COMPOSER_LIMITS.maxAttachmentText} karakterle sınırlandı.]\n` : ''; return `\n\n[Ekli dosya: ${file.name}]\n---\n${clipped}${notice}---\n`; }
export async function copyText(text: string, documentRef: Document = document): Promise<boolean> { if (!text) return false; try { await navigator.clipboard.writeText(text); return true; } catch { const helper = documentRef.createElement('textarea'); helper.value = text; helper.readOnly = true; helper.style.position = 'fixed'; helper.style.opacity = '0'; documentRef.body.append(helper); helper.select(); let copied = false; try { copied = documentRef.execCommand('copy'); } catch { copied = false; } helper.remove(); return copied; } }

export function installChatComposerFeatures(documentRef: Document = document, rootRef: ComposerRoot = window): () => void {
  const composer = documentRef.querySelector<ComposerForm>('#composer'); const attachButton = documentRef.querySelector<HTMLButtonElement>('#attachBtn'); const input = documentRef.querySelector<HTMLTextAreaElement>('#messageInput'); const messages = documentRef.querySelector<HTMLElement>('#messages'); const toast = documentRef.querySelector<HTMLElement>('#toast');
  if (!composer || !attachButton || !input || !messages) return () => undefined;
  const announce = (message: string): void => { if (!toast || !message) return; toast.textContent = message; toast.classList.remove('hidden'); window.setTimeout(() => toast.classList.add('hidden'), 3200); };
  const renderAttachments = (): void => { const files = composer._hafizeAttachments ?? []; let strip = composer.querySelector<HTMLElement>('.attachment-strip'); if (!files.length) { strip?.remove(); return; } if (!strip) { strip = documentRef.createElement('div'); strip.className = 'attachment-strip'; strip.setAttribute('aria-label', 'Eklenen dosyalar'); composer.insertBefore(strip, composer.querySelector('.composer-row')); } strip.replaceChildren(); files.forEach((file, index) => { const chip = documentRef.createElement('span'); chip.className = 'attachment-chip'; chip.textContent = `${file.name} · ${(file.size / 1024).toFixed(1)} KB`; const remove = documentRef.createElement('button'); remove.type = 'button'; remove.className = 'attachment-remove'; remove.textContent = '×'; remove.setAttribute('aria-label', `${file.name} ekini kaldır`); remove.addEventListener('click', () => { const at = input.value.lastIndexOf(file.block); if (at >= 0) input.value = `${input.value.slice(0, at)}${input.value.slice(at + file.block.length)}`; files.splice(index, 1); input.dispatchEvent(new Event('input', { bubbles: true })); renderAttachments(); input.focus(); }); chip.append(remove); strip.append(chip); }); };
  const addFile = async (file: File): Promise<void> => { const files = composer._hafizeAttachments ?? (composer._hafizeAttachments = []); if (files.length >= COMPOSER_LIMITS.maxAttachments) return announce(`En fazla ${COMPOSER_LIMITS.maxAttachments} dosya ekleyebilirsin.`); if (!acceptedFile(file)) return announce('Bu dosya türü desteklenmiyor veya dosya 384 KB sınırını aşıyor.'); if (files.some((item) => item.name === file.name && item.size === file.size && item.lastModified === file.lastModified)) return announce('Bu dosya zaten eklendi.'); try { const source = await file.text(); if (!source.trim()) return announce(`${file.name} boş olduğu için eklenmedi.`); const before = input.value; const block = composeAttachment(file, source); const next = `${before}${block}`.slice(0, input.maxLength || 12000); const appended = next.slice(before.length); if (!appended) return announce('Mesaj alanı dolu.'); files.push(Object.freeze({ name: file.name, size: file.size, lastModified: file.lastModified, block: appended })); input.value = next; input.dispatchEvent(new Event('input', { bubbles: true })); renderAttachments(); input.focus(); announce(`${file.name} mesaja eklendi. Dosya ayrı bir yükleme olarak gönderilmedi.`); } catch { announce(`${file.name} okunamadı.`); } };
  const picker = (): void => { if (input.disabled) return; const fileInput = documentRef.createElement('input'); fileInput.type = 'file'; fileInput.hidden = true; fileInput.multiple = true; fileInput.accept = '.txt,.md,.markdown,.json,.csv,.tsv,.html,.css,.js,.mjs,.cjs,.jsx,.tsx,.py,.java,.c,.h,.cpp,.hpp,.xml,.yaml,.yml,.toml,.ini,.log,text/plain,application/json'; fileInput.addEventListener('change', async () => { for (const file of [...(fileInput.files ?? [])].slice(0, COMPOSER_LIMITS.maxAttachments)) await addFile(file); fileInput.remove(); }, { once: true }); documentRef.body.append(fileInput); fileInput.click(); };
  const findRetryPrompt = (article: Element): string => { let cursor = article.previousElementSibling; while (cursor) { if (cursor.classList.contains('user')) return cursor.querySelector('.content')?.textContent?.trim() || ''; cursor = cursor.previousElementSibling; } return ''; };
  const onAssistant = (article: HTMLElement): void => { if (article.querySelector('.message-actions')) return; const content = article.querySelector<HTMLElement>('.content'); if (!content) return; const actions = documentRef.createElement('div'); actions.className = 'message-actions'; const copy = documentRef.createElement('button'); copy.type = 'button'; copy.className = 'message-action'; copy.textContent = 'Kopyala'; copy.addEventListener('click', async () => { const ok = await copyText(content.textContent?.trim() || '', documentRef); if (!ok) announce('Yanıt panoya kopyalanamadı.'); else { copy.textContent = 'Kopyalandı'; rootRef.setTimeout(() => { copy.textContent = 'Kopyala'; }, 1400); } }); const retry = documentRef.createElement('button'); retry.type = 'button'; retry.className = 'message-action'; retry.textContent = 'Yeniden dene'; retry.addEventListener('click', () => { const prompt = findRetryPrompt(article); if (!prompt || input.disabled) return; input.value = prompt; input.dispatchEvent(new Event('input', { bubbles: true })); composer.requestSubmit(); }); actions.append(copy, retry); article.append(actions); };
  const onUser = (article: HTMLElement): void => { if (article.querySelector('.message-actions')) return; const messageId = article.dataset.messageId; if (!messageId) return; const actions = documentRef.createElement('div'); actions.className = 'message-actions'; const edit = documentRef.createElement('button'); edit.type = 'button'; edit.className = 'message-action'; edit.textContent = 'Düzenle'; edit.addEventListener('click', () => rootRef.dispatchEvent(new CustomEvent('hafize:edit-message', { detail: { messageId } }))); actions.append(edit); article.append(actions); };
  const onAttach = (event: Event): void => { event.preventDefault(); event.stopImmediatePropagation(); picker(); }; attachButton.addEventListener('click', onAttach, true);
  const onDrop = async (event: DragEvent): Promise<void> => { event.preventDefault(); composer.classList.remove('drag-active'); for (const file of [...(event.dataTransfer?.files ?? [])].slice(0, COMPOSER_LIMITS.maxAttachments)) await addFile(file); }; composer.addEventListener('dragover', (event) => { event.preventDefault(); composer.classList.add('drag-active'); }); composer.addEventListener('dragleave', () => composer.classList.remove('drag-active')); composer.addEventListener('drop', onDrop);
  const onPaste = async (event: ClipboardEvent): Promise<void> => { const files = [...(event.clipboardData?.files ?? [])]; if (!files.length) return; event.preventDefault(); for (const file of files.slice(0, COMPOSER_LIMITS.maxAttachments)) await addFile(file); }; input.addEventListener('paste', onPaste);
  const onSubmit = (): void => { composer._hafizeAttachments = []; renderAttachments(); }; composer.addEventListener('submit', onSubmit, true);
  const observer = new MutationObserver(() => { messages.querySelectorAll<HTMLElement>('.message.assistant').forEach(onAssistant); messages.querySelectorAll<HTMLElement>('.message.user').forEach(onUser); }); observer.observe(messages, { childList: true }); observer.takeRecords(); messages.querySelectorAll<HTMLElement>('.message.assistant').forEach(onAssistant); messages.querySelectorAll<HTMLElement>('.message.user').forEach(onUser);
  renderAttachments();
  return () => { observer.disconnect(); attachButton.removeEventListener('click', onAttach, true); composer.removeEventListener('dragover', () => undefined); composer.removeEventListener('dragleave', () => undefined); composer.removeEventListener('drop', onDrop); input.removeEventListener('paste', onPaste); composer.removeEventListener('submit', onSubmit, true); };
}

if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', () => { void installChatComposerFeatures(); }, { once: true }); else void installChatComposerFeatures();
