export interface ManagedConversation { readonly id: string; title?: string; pinned?: boolean; }
const STORAGE_KEY = 'hafize.conversations.v1';
const MAX_TITLE = 80;
export function normalizeConversationTitle(value: unknown): string { return typeof value === 'string' ? value.replace(/\s+/g, ' ').trim().slice(0, MAX_TITLE) || 'Yeni sohbet' : 'Yeni sohbet'; }
function readHistory(): ManagedConversation[] { try { const value: unknown = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'); return Array.isArray(value) ? value.filter((item): item is ManagedConversation => Boolean(item && typeof item === 'object' && typeof (item as Record<string, unknown>).id === 'string')) : []; } catch { return []; } }
function writeHistory(records: readonly ManagedConversation[]): boolean { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(records.slice(0, 30))); return true; } catch { return false; } }
function findConversation(id: string): ManagedConversation | null { return readHistory().find((item) => item.id === id) ?? null; }
export function installConversationHistoryManagement(documentRef: Document = document, rootRef: Window = window): () => void { const list = documentRef.querySelector<HTMLElement>('#conversationList'); if (!list) return () => undefined; const announce = (message: string): void => { const toast = documentRef.querySelector<HTMLElement>('#toast'); if (!toast) return; toast.textContent = message; toast.classList.remove('hidden'); rootRef.setTimeout(() => toast.classList.add('hidden'), 2600); };
  const getId = (row: Element): string => row.querySelector<HTMLElement>('.conversation-open')?.dataset.conversationId || '';
  const mutate = (id: string, fn: (record: ManagedConversation) => void): boolean => { const history = readHistory(); const record = history.find((item) => item.id === id); if (!record) return false; fn(record); return writeHistory(history); };
  const buttons = (row: HTMLElement, record: ManagedConversation): void => { const open = row.querySelector<HTMLElement>('.conversation-open'); if (!open) return; open.dataset.conversationId = record.id; open.textContent = normalizeConversationTitle(record.title); open.title = open.textContent; row.classList.toggle('pinned', record.pinned === true); let actions = row.querySelector<HTMLElement>('.history-manage'); if (!actions) { actions = documentRef.createElement('div'); actions.className = 'history-manage'; actions.setAttribute('aria-label', 'Sohbet işlemleri'); row.append(actions); } actions.replaceChildren(); const pin = documentRef.createElement('button'); pin.type = 'button'; pin.className = 'history-manage-btn'; pin.textContent = record.pinned ? '◆' : '◇'; pin.setAttribute('aria-label', record.pinned ? 'Sohbet sabitlemesini kaldır' : 'Sohbeti sabitle'); pin.setAttribute('aria-pressed', String(record.pinned === true)); const rename = documentRef.createElement('button'); rename.type = 'button'; rename.className = 'history-manage-btn'; rename.textContent = '✎'; rename.setAttribute('aria-label', 'Sohbet adını değiştir'); pin.addEventListener('click', (event) => { event.preventDefault(); event.stopPropagation(); const changed = mutate(record.id, (item) => { item.pinned = !Boolean(item.pinned); }); if (changed) { sync(); announce(record.pinned ? 'Sohbet sabitlendi.' : 'Sohbet sabitlemesi kaldırıldı.'); } }); rename.addEventListener('click', (event) => { event.preventDefault(); event.stopPropagation(); openRename(row, findConversation(record.id) || record); }); actions.append(pin, rename); };
  const openRename = (row: HTMLElement, record: ManagedConversation): void => { row.querySelector('.history-rename')?.remove(); const wrapper = documentRef.createElement('div'); wrapper.className = 'history-rename'; wrapper.setAttribute('role', 'group'); wrapper.setAttribute('aria-label', 'Sohbet adını düzenle'); const input = documentRef.createElement('input'); input.type = 'text'; input.maxLength = MAX_TITLE; input.value = normalizeConversationTitle(record.title); input.setAttribute('aria-label', 'Yeni sohbet adı'); const cancel = documentRef.createElement('button'); cancel.type = 'button'; cancel.textContent = 'Vazgeç'; const save = documentRef.createElement('button'); save.type = 'button'; save.className = 'primary'; save.textContent = 'Kaydet'; const commit = (): void => { const title = normalizeConversationTitle(input.value); if (!title) return announce('Sohbet adı boş olamaz.'); if (!mutate(record.id, (item) => { item.title = title; })) return; row.querySelector<HTMLElement>('.conversation-open')!.textContent = title; row.querySelector<HTMLElement>('.conversation-open')!.title = title; wrapper.remove(); announce('Sohbet adı güncellendi.'); }; cancel.addEventListener('click', () => wrapper.remove()); save.addEventListener('click', commit); input.addEventListener('keydown', (event) => { if (event.key === 'Enter') { event.preventDefault(); commit(); } else if (event.key === 'Escape') { event.preventDefault(); wrapper.remove(); } }); wrapper.append(input, cancel, save); row.append(wrapper); input.focus(); input.select(); };
  const sync = (): void => { const records = readHistory(); const byId = new Map(records.map((record) => [record.id, record])); const rows = [...list.querySelectorAll<HTMLElement>('.conversation-row')]; rows.forEach((row, index) => { const id = getId(row) || records[index]?.id; if (!id) return; const record = byId.get(id); if (record) buttons(row, record); }); rows.sort((a, b) => Number(b.classList.contains('pinned')) - Number(a.classList.contains('pinned'))).forEach((row) => list.append(row)); };
  const observer = new MutationObserver(sync); observer.observe(list, { childList: true, subtree: true }); const onStorage = (event: StorageEvent): void => { if (event.key === STORAGE_KEY) sync(); }; rootRef.addEventListener('storage', onStorage); sync(); return () => { observer.disconnect(); rootRef.removeEventListener('storage', onStorage); };
}
const boot = (): void => { void installConversationHistoryManagement(); }; if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot, { once: true }); else void installConversationHistoryManagement();
