export interface SearchableConversation { readonly title?: string; readonly agentId?: string; readonly messages?: readonly { readonly content?: string }[]; }
const STORAGE_KEY = 'hafize.conversations.v1';
const normalize = (value: unknown): string => typeof value === 'string' ? value.toLocaleLowerCase('tr-TR').replace(/\s+/g, ' ').trim() : '';
export function searchableText(conversation: SearchableConversation): string { return normalize([conversation.title, conversation.agentId, ...(conversation.messages ?? []).map((message) => message.content)].filter(Boolean).join(' ')); }
export function conversationMatches(conversation: SearchableConversation, query: string): boolean { const wanted = normalize(query); return !wanted || searchableText(conversation).includes(wanted); }
function readConversations(): SearchableConversation[] { try { const parsed: unknown = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'); return Array.isArray(parsed) ? parsed.filter((item): item is SearchableConversation => Boolean(item && typeof item === 'object')) : []; } catch { return []; } }
export function installConversationSearch(documentRef: Document = document, rootRef: Window = window): () => void {
  const block = documentRef.querySelector<HTMLElement>('.history-block'); const history = documentRef.querySelector<HTMLElement>('#conversationList'); if (!block || !history) return () => undefined;
  const section = documentRef.createElement('section'); section.className = 'history-search'; section.setAttribute('aria-label', 'Sohbet geçmişinde ara');
  const label = documentRef.createElement('label'); label.className = 'history-search-label'; label.htmlFor = 'conversationSearchInput'; label.textContent = 'Sohbetlerde ara';
  const row = documentRef.createElement('div'); row.className = 'history-search-row'; const input = documentRef.createElement('input'); input.id = 'conversationSearchInput'; input.className = 'history-search-input'; input.type = 'search'; input.autocomplete = 'off'; input.spellcheck = false; input.placeholder = 'Başlık veya mesaj…'; input.maxLength = 120; input.setAttribute('aria-describedby', 'conversationSearchStatus'); const clear = documentRef.createElement('button'); clear.type = 'button'; clear.className = 'history-search-clear'; clear.textContent = '×'; clear.setAttribute('aria-label', 'Sohbet aramasını temizle'); clear.hidden = true; row.append(input, clear);
  const status = documentRef.createElement('div'); status.id = 'conversationSearchStatus'; status.className = 'history-search-status'; status.setAttribute('role', 'status'); status.setAttribute('aria-live', 'polite'); section.append(label, row, status); block.insertBefore(section, block.querySelector('.history-head')?.nextSibling || history);
  let query = ''; let queued = false;
  const render = (): void => { const wanted = normalize(query); const stored = readConversations(); const rows = [...history.querySelectorAll<HTMLElement>('.conversation-row')]; const byTitle = new Map(stored.map((conversation) => [normalize(conversation.title), conversation])); let visible = 0; rows.forEach((node) => { const title = normalize(node.querySelector('.conversation-open')?.textContent || ''); const conversation = byTitle.get(title); const match = conversation ? conversationMatches(conversation, wanted) : !wanted || title.includes(wanted); node.hidden = !match; if (match) visible += 1; }); clear.hidden = !wanted; status.textContent = !rows.length ? 'Henüz sohbet yok.' : !wanted ? `${rows.length} sohbet` : `${visible} / ${rows.length} sohbet eşleşti`; const empty = history.querySelector<HTMLElement>('.history-search-empty'); if (wanted && rows.length && visible === 0) { const node = empty || documentRef.createElement('div'); node.className = 'history-search-empty'; node.setAttribute('role', 'status'); node.textContent = 'Aramanla eşleşen sohbet bulunamadı.'; if (!empty) history.append(node); } else empty?.remove(); };
  const queue = (): void => { if (queued) return; queued = true; rootRef.requestAnimationFrame(() => { queued = false; render(); }); };
  const onInput = (): void => { query = input.value; queue(); }; const onClear = (): void => { input.value = ''; query = ''; queue(); input.focus(); }; const onKey = (event: KeyboardEvent): void => { if (event.key === 'Escape' && input.value) { event.preventDefault(); onClear(); return; } if ((event.ctrlKey || event.metaKey) && event.shiftKey && event.key.toLowerCase() === 'f') { const target = event.target as Element | null; if (target && ['INPUT', 'TEXTAREA', 'SELECT'].includes(target.tagName) && target !== input) return; event.preventDefault(); input.focus(); input.select(); } };
  input.addEventListener('input', onInput); clear.addEventListener('click', onClear); documentRef.addEventListener('keydown', onKey); const observer = new MutationObserver(queue); observer.observe(history, { childList: true, subtree: true }); const onStorage = (event: StorageEvent): void => { if (event.key === STORAGE_KEY) queue(); }; rootRef.addEventListener('storage', onStorage); render();
  return () => { observer.disconnect(); input.removeEventListener('input', onInput); clear.removeEventListener('click', onClear); documentRef.removeEventListener('keydown', onKey); rootRef.removeEventListener('storage', onStorage); section.remove(); };
}
const boot = (): void => { void installConversationSearch(); }; if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot, { once: true }); else void installConversationSearch();
