export interface PromptUsageRecord { readonly id: string; readonly title?: string; readonly useCount?: number; readonly updatedAt?: string; }
export interface PromptUsageSummary { readonly total: number; readonly usedCount: number; readonly totalUses: number; readonly top: readonly PromptUsageRecord[]; readonly recent: readonly PromptUsageRecord[]; }
export type UsageController = Readonly<{ readonly mounted: true; readonly refresh: () => void; readonly summarize: () => PromptUsageSummary; readonly destroy: () => void }>;
interface UsageRoot extends Window { HafizePromptLibraryUsage?: Readonly<{ readonly STORAGE_KEY: string; readonly mount: () => UsageController | null; readonly summarize: (items: readonly PromptUsageRecord[]) => PromptUsageSummary; readonly usageOf: (item: PromptUsageRecord) => number; }>; }
const root = globalThis as UsageRoot;
const STORAGE_KEY = 'hafize.prompt-library.v1';
const CARD_ID = 'promptLibraryCard';
const INSIGHTS_ID = 'promptLibraryUsageInsights';
const MAX_ITEMS = 5;
const MAX_TEXT = 72;
const make = <K extends keyof HTMLElementTagNameMap>(doc: Document, tag: K, value?: string, className?: string): HTMLElementTagNameMap[K] => { const node = doc.createElement(tag); if (className) node.className = className; if (value !== undefined) node.textContent = value; return node; };
function readItems(windowRef: UsageRoot): PromptUsageRecord[] { try { const items: unknown = JSON.parse(windowRef.localStorage?.getItem(STORAGE_KEY) || '[]'); return Array.isArray(items) ? items.filter((item): item is PromptUsageRecord => typeof item === 'object' && item !== null) : []; } catch { return []; } }
function titleOf(item: PromptUsageRecord): string { return (typeof item.title === 'string' ? item.title.trim() : '').slice(0, MAX_TEXT) || 'İsimsiz istem'; }
export function usageOf(item: PromptUsageRecord): number { const value = Number(item.useCount); return Number.isFinite(value) && value >= 0 ? Math.min(9999, Math.floor(value)) : 0; }
function dateValue(item: PromptUsageRecord): number { const value = Date.parse(typeof item.updatedAt === 'string' ? item.updatedAt : ''); return Number.isFinite(value) ? value : 0; }
export function summarize(items: readonly PromptUsageRecord[]): PromptUsageSummary { const valid = items.filter((item) => typeof item.id === 'string'); const used = valid.filter((item) => usageOf(item) > 0); const totalUses = valid.reduce((sum, item) => sum + usageOf(item), 0); const top = [...used].sort((a, b) => usageOf(b) - usageOf(a) || dateValue(b) - dateValue(a)).slice(0, MAX_ITEMS); const recent = [...used].sort((a, b) => dateValue(b) - dateValue(a) || usageOf(b) - usageOf(a)).slice(0, MAX_ITEMS); return Object.freeze({ total: valid.length, usedCount: used.length, totalUses, top, recent }); }
function button(doc: Document, label: string): HTMLButtonElement { const node = make(doc, 'button', label, 'mini-btn prompt-library-usage-toggle'); node.type = 'button'; return node; }
export function mount(documentRef: Document = root.document, rootRef: UsageRoot = root): UsageController | null {
  const card = documentRef?.getElementById(CARD_ID); if (!documentRef || !card || documentRef.getElementById(INSIGHTS_ID)) return null;
  const section = make(documentRef, 'section', undefined, 'prompt-library-usage-insights'); section.id = INSIGHTS_ID; section.setAttribute('aria-labelledby', 'promptLibraryUsageTitle');
  const heading = make(documentRef, 'div', undefined, 'prompt-library-usage-head'); const title = make(documentRef, 'strong', 'Kullanım istatistikleri'); title.id = 'promptLibraryUsageTitle'; const toggle = button(documentRef, 'Gizle'); toggle.setAttribute('aria-expanded', 'true'); const body = make(documentRef, 'div', undefined, 'prompt-library-usage-body'); heading.append(title, toggle); section.append(heading, body); card.append(section);
  const renderList = (items: readonly PromptUsageRecord[], emptyLabel: string): HTMLElement => { const list = make(documentRef, 'div', undefined, 'prompt-library-usage-list'); list.setAttribute('role', 'list'); if (!items.length) { list.append(make(documentRef, 'span', emptyLabel, 'prompt-library-usage-empty')); return list; } items.forEach((item, index) => { const row = make(documentRef, 'div', undefined, 'prompt-library-usage-row'); row.setAttribute('role', 'listitem'); row.append(make(documentRef, 'span', `${index + 1}.`, 'prompt-library-usage-rank'), make(documentRef, 'span', titleOf(item), 'prompt-library-usage-name'), make(documentRef, 'span', `${usageOf(item)} kullanım`, 'prompt-library-usage-count')); list.append(row); }); return list; };
  const render = (): void => { if (!documentRef.getElementById(INSIGHTS_ID)) return; const summary = summarize(readItems(rootRef)); body.replaceChildren(); const stats = make(documentRef, 'div', undefined, 'prompt-library-usage-stats'); for (const [label, value] of [['Kayıt', summary.total], ['Kullanılan', summary.usedCount], ['Toplam kullanım', summary.totalUses]] as const) { const stat = make(documentRef, 'div', undefined, 'prompt-library-usage-stat'); stat.append(make(documentRef, 'span', String(value), 'prompt-library-usage-value'), make(documentRef, 'span', label, 'prompt-library-usage-label')); stats.append(stat); } body.append(stats, make(documentRef, 'span', 'En çok kullanılan', 'prompt-library-usage-subtitle'), renderList(summary.top, 'Henüz kullanılan istem yok.'), make(documentRef, 'span', 'Son kullanılan', 'prompt-library-usage-subtitle'), renderList(summary.recent, 'Son kullanım verisi bulunmuyor.')); };
  let hidden = false; const onToggle = (): void => { hidden = !hidden; body.hidden = hidden; toggle.textContent = hidden ? 'Göster' : 'Gizle'; toggle.setAttribute('aria-expanded', String(!hidden)); };
  let timer: number | undefined; const schedule = (): void => { if (timer !== undefined) rootRef.clearTimeout(timer); timer = rootRef.setTimeout(render, 80); };
  const list = documentRef.getElementById('promptLibraryList'); const observer = new MutationObserver(schedule); observer.observe(list || card, { childList: true, subtree: true }); const onStorage = (event: StorageEvent): void => { if (event.key === STORAGE_KEY) render(); };
  toggle.addEventListener('click', onToggle); rootRef.addEventListener('storage', onStorage); render();
  return Object.freeze({ mounted: true, refresh: render, summarize: () => summarize(readItems(rootRef)), destroy: () => { if (timer !== undefined) rootRef.clearTimeout(timer); observer.disconnect(); rootRef.removeEventListener('storage', onStorage); toggle.removeEventListener('click', onToggle); section.remove(); } });
}
export const HafizePromptLibraryUsage = Object.freeze({ STORAGE_KEY, mount, summarize, usageOf }); root.HafizePromptLibraryUsage = HafizePromptLibraryUsage;
const start = (): void => { void mount(document, root); }; if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start, { once: true }); else start();
