export type ScheduleStatus = 'scheduled' | 'running' | 'completed' | 'failed' | 'cancelled';
export interface ScheduledTaskRecord { readonly scheduleId: string; readonly status: ScheduleStatus; readonly task: string; readonly runAt: string; readonly agentId: string; readonly attempts: number; readonly maxAttempts: number; readonly traceId?: string; readonly lastError?: string; }
interface SchedulePayload { readonly schedules?: readonly ScheduledTaskRecord[]; readonly [key: string]: unknown; }
interface ScheduleError extends Error { readonly status?: number; readonly payload?: unknown; }
interface ScheduleRoot extends Window { ScheduledTasksWorkspace?: Readonly<{ open: () => void; close: () => void; refresh: () => Promise<void> }>; }

const root = globalThis as ScheduleRoot;
const API_PATH = '/api/schedules';
const PANEL_ID = 'scheduledTasksWorkspace';
const MAX_TASK = 20_000;
const MAX_LIST = 128;
const MAX_ATTEMPTS = 5;
const REFRESH_MS = 30_000;

const text = (value: unknown, limit: number): string => String(value ?? '').slice(0, limit);
const el = <K extends keyof HTMLElementTagNameMap>(tag: K, value?: string, className?: string): HTMLElementTagNameMap[K] => { const node = document.createElement(tag); if (className) node.className = className; if (value !== undefined) node.textContent = value; return node; };
const button = (label: string, action: string, className = 'soft-btn'): HTMLButtonElement => { const node = el('button', label, className); node.type = 'button'; node.dataset.taskAction = action; return node; };
const statusText = (value: ScheduleStatus): string => ({ scheduled: 'Planlandı', running: 'Çalışıyor', completed: 'Tamamlandı', failed: 'Başarısız', cancelled: 'İptal edildi' } as const)[value] || 'Bilinmiyor';

async function request<T extends SchedulePayload = SchedulePayload>(path = API_PATH, options: RequestInit = {}): Promise<T> {
  const response = await root.fetch(path, { ...options, credentials: 'same-origin', headers: { Accept: 'application/json', ...(options.body ? { 'Content-Type': 'application/json' } : {}), ...(options.headers || {}) } });
  let payload: T | null = null; try { payload = await response.json() as T; } catch { /* empty response */ }
  if (!response.ok) { const error = new Error(text((payload as Record<string, unknown> | null)?.code || (payload as Record<string, unknown> | null)?.error || `HTTP_${response.status}`)) as ScheduleError; Object.defineProperty(error, 'status', { value: response.status }); Object.defineProperty(error, 'payload', { value: payload }); throw error; }
  return payload || {} as T;
}

function localDateTimeValue(offsetMinutes = 5): string { const date = new Date(Date.now() + offsetMinutes * 60_000); const pad = (value: number): string => String(value).padStart(2, '0'); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`; }
function isoFromLocal(value: string): string { const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : date.toISOString(); }
function formattedDate(value: string): string { const timestamp = Date.parse(value); return Number.isFinite(timestamp) ? new Intl.DateTimeFormat('tr-TR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(timestamp)) : 'Tarih bilinmiyor'; }

export function mountScheduledTasks(documentRef: Document = document): Readonly<{ open: () => void; close: () => void; refresh: () => Promise<void> }> | null {
  if (!documentRef || documentRef.getElementById(PANEL_ID)) return null;
  const panel = el('section', undefined, 'scheduled-tasks-overlay'); panel.id = PANEL_ID; panel.hidden = true; panel.setAttribute('role', 'dialog'); panel.setAttribute('aria-modal', 'true'); panel.setAttribute('aria-labelledby', 'scheduledTasksTitle');
  const shell = el('div', undefined, 'scheduled-tasks-shell'); const head = el('div', undefined, 'scheduled-tasks-head'); const title = el('strong', 'Zamanlanmış görevler', 'scheduled-tasks-title'); title.id = 'scheduledTasksTitle'; head.append(title, button('Yenile', 'refresh', 'mini-btn'), button('Kapat', 'close', 'mini-btn'));
  const create = el('form', undefined, 'scheduled-tasks-create'); create.noValidate = true; create.append(el('div', 'Yeni görev planla', 'scheduled-tasks-section-title'));
  const agentLabel = el('label', 'Ajan'); const agent = documentRef.createElement('select'); agent.id = 'scheduledTaskAgent'; agent.required = true; agent.setAttribute('aria-label', 'Zamanlanmış görev ajanı'); documentRef.querySelectorAll<HTMLOptionElement>('#agentSelect option').forEach((option) => { if (!option.value) return; const next = el('option', option.textContent || option.value); next.value = option.value; agent.append(next); }); if (!agent.options.length) { const option = el('option', 'Ajanlar yükleniyor…'); option.value = ''; agent.append(option); agent.disabled = true; } agentLabel.append(agent);
  const taskLabel = el('label', 'Görev metni'); const task = documentRef.createElement('textarea'); task.rows = 5; task.maxLength = MAX_TASK; task.required = true; task.placeholder = 'Örn. Bugünkü önemli gelişmeleri özetle.'; task.setAttribute('aria-label', 'Zamanlanacak görev metni'); taskLabel.append(task);
  const whenLabel = el('label', 'Çalıştırma zamanı'); const when = documentRef.createElement('input'); when.type = 'datetime-local'; when.required = true; when.value = localDateTimeValue(); when.min = localDateTimeValue(); whenLabel.append(when);
  const attemptsLabel = el('label', 'Maksimum deneme'); const attempts = documentRef.createElement('select'); attempts.setAttribute('aria-label', 'Maksimum deneme sayısı'); for (let i = 1; i <= MAX_ATTEMPTS; i += 1) { const option = el('option', String(i)); option.value = String(i); attempts.append(option); } attemptsLabel.append(attempts);
  const grid = el('div', undefined, 'scheduled-tasks-form-grid'); grid.append(agentLabel, whenLabel, attemptsLabel); const submit = button('Görevi planla', 'create'); submit.classList.add('primary'); create.append(taskLabel, grid, submit);
  const listSection = el('section', undefined, 'scheduled-tasks-list-section'); listSection.setAttribute('aria-label', 'Planlanmış görevler listesi'); listSection.append(el('div', 'Planlanan görevler', 'scheduled-tasks-section-title')); const filter = el('div', undefined, 'scheduled-tasks-filter'); const filterSelect = documentRef.createElement('select'); filterSelect.setAttribute('aria-label', 'Görev durumuna göre filtrele'); const statuses: readonly [string, string][] = [['all', 'Tümü'], ['scheduled', 'Planlandı'], ['running', 'Çalışıyor'], ['completed', 'Tamamlandı'], ['failed', 'Başarısız'], ['cancelled', 'İptal edildi']]; statuses.forEach(([value, label]) => { const option = el('option', label); option.value = value; filterSelect.append(option); }); const filterInfo = el('span', '', 'scheduled-tasks-filter-info'); filter.append(filterSelect, filterInfo); const list = el('div', undefined, 'scheduled-tasks-list'); list.setAttribute('role', 'list'); listSection.append(filter, list);
  const status = el('div', '', 'scheduled-tasks-status'); status.setAttribute('role', 'status'); status.setAttribute('aria-live', 'polite'); shell.append(head, create, status, listSection); panel.append(shell); documentRef.body.append(panel);
  let selectedStatus = 'all'; let timer = 0; let lastFocus: Element | null = null;
  const notify = (message: string, tone = ''): void => { status.textContent = text(message, 220); status.dataset.tone = tone; };
  const renderRow = (entry: ScheduledTaskRecord): HTMLElement => { const item = el('article', undefined, 'scheduled-task-row'); item.dataset.scheduleId = text(entry.scheduleId, 120); item.dataset.status = entry.status; item.dataset.runAt = text(entry.runAt, 40); item.setAttribute('role', 'listitem'); const rowHead = el('div', undefined, 'scheduled-task-row-head'); rowHead.append(el('strong', text(entry.task, 120)), el('span', statusText(entry.status), `scheduled-task-status status-${entry.status}`)); const meta = el('div', `${formattedDate(entry.runAt)} · ${text(entry.agentId, 80)} · deneme ${Math.max(0, Math.floor(entry.attempts))}/${Math.max(1, Math.floor(entry.maxAttempts))}`, 'scheduled-task-meta'); const detail = el('p', entry.lastError ? `Son hata: ${text(entry.lastError, 120)}` : entry.status === 'completed' ? 'Başarıyla tamamlandı.' : ''); const actions = el('div', undefined, 'scheduled-task-actions'); if (entry.status === 'scheduled') actions.append(button('İptal et', 'cancel', 'mini-btn')); const trace = button('Trace ID', 'trace', 'mini-btn'); trace.title = text(entry.traceId, 128); actions.append(trace); item.append(rowHead, meta, detail, actions); return item; };
  const applyFilter = (): void => { const rows = [...list.querySelectorAll<HTMLElement>('.scheduled-task-row')]; const visible = rows.filter((row) => selectedStatus === 'all' || row.dataset.status === selectedStatus); rows.forEach((row) => { row.hidden = !visible.includes(row); }); filterInfo.textContent = `${visible.length} görev gösteriliyor.`; };
  const refresh = async (): Promise<void> => { list.replaceChildren(el('div', 'Görevler yükleniyor…', 'scheduled-tasks-empty')); try { const payload = await request(); const entries = [...(payload.schedules || [])].slice(0, MAX_LIST); entries.sort((a, b) => String(a.runAt).localeCompare(String(b.runAt)) || String(a.scheduleId).localeCompare(String(b.scheduleId))); list.replaceChildren(); if (!entries.length) list.append(el('div', 'Henüz planlanmış görev yok.', 'scheduled-tasks-empty')); else entries.forEach((entry) => list.append(renderRow(entry))); applyFilter(); } catch (error) { list.replaceChildren(el('div', (error as ScheduleError).status === 401 ? 'Görevleri görmek için oturum açmalısın.' : 'Görev listesi yüklenemedi.', 'scheduled-tasks-empty')); notify((error as ScheduleError).status === 401 ? 'Kimlik doğrulama gerekli.' : 'Görev servisine ulaşılamadı.', 'error'); } };
  create.addEventListener('submit', async (event) => { event.preventDefault(); const taskText = task.value.trim(); const runAt = isoFromLocal(when.value); if (!agent.value) return notify('Geçerli bir ajan seçmelisin.', 'error'); if (!taskText) return notify('Görev metni boş olamaz.', 'error'); if (!runAt || Date.parse(runAt) <= Date.now()) return notify('Çalıştırma zamanı gelecekte olmalı.', 'error'); submit.disabled = true; try { await request(API_PATH, { method: 'POST', body: JSON.stringify({ agentId: agent.value, task: taskText, runAt, maxAttempts: Number(attempts.value) }) }); task.value = ''; when.value = localDateTimeValue(); notify('Görev planlandı.', 'success'); await refresh(); } catch { notify('Görev planlanamadı.', 'error'); } finally { submit.disabled = false; } });
  filterSelect.addEventListener('change', () => { selectedStatus = filterSelect.value; applyFilter(); });
  panel.addEventListener('click', async (event) => { const target = (event.target as Element | null)?.closest<HTMLElement>('[data-task-action]'); if (!target) return; const action = target.dataset.taskAction; if (action === 'close') close(); else if (action === 'refresh') await refresh(); else if (action === 'trace') notify(`Trace ID: ${target.getAttribute('title') || ''}`, 'info'); else if (action === 'cancel') { const id = target.closest<HTMLElement>('.scheduled-task-row')?.dataset.scheduleId; if (!id || !root.confirm?.('Bu planlanmış görev iptal edilsin mi?')) return; try { await request(`${API_PATH}/${encodeURIComponent(id)}`, { method: 'DELETE' }); notify('Görev iptal edildi.', 'success'); await refresh(); } catch { notify('Görev iptal edilemedi.', 'error'); } } });
  const onKeyDown = (event: KeyboardEvent): void => { if (event.key === 'Escape' && !panel.hidden) close(); };
  documentRef.addEventListener('keydown', onKeyDown);
  const open = (): void => { lastFocus = documentRef.activeElement; panel.hidden = false; filterSelect.value = 'all'; selectedStatus = 'all'; void refresh(); window.clearInterval(timer); timer = window.setInterval(() => { void refresh(); }, REFRESH_MS); panel.querySelector<HTMLButtonElement>('[data-task-action="close"]')?.focus(); };
  const close = (): void => { panel.hidden = true; window.clearInterval(timer); timer = 0; lastFocus instanceof HTMLElement && lastFocus.focus(); };
  const nav = [...documentRef.querySelectorAll<HTMLElement>('.nav-item')].find((node) => node.textContent?.includes('Görevler'));
  if (nav) { nav.disabled = false; nav.setAttribute('aria-controls', PANEL_ID); nav.setAttribute('aria-expanded', 'false'); nav.addEventListener('click', open); }
  const controller = Object.freeze({ open, close, refresh }); root.ScheduledTasksWorkspace = controller;
  return controller;
}

const boot = (): void => { mountScheduledTasks(document); };
if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot, { once: true }); else boot();
