export type ThemeName = 'light' | 'dark';
export interface CalendarCell { readonly day: number; readonly month: number; readonly year: number; readonly outside: boolean; readonly selected: boolean; }
export interface SidebarController { readonly isOpen: () => boolean; readonly close: () => void; readonly destroy: () => void; }
export interface UiShellController { readonly getTheme: () => ThemeName; readonly renderCalendar: () => void; readonly sidebarDisclosure: SidebarController | null; readonly destroy: () => void; }
interface UiShellRoot extends Window { HafizeUiShell?: Readonly<{ install: (documentRef: Document, root: UiShellRoot) => UiShellController | null }> }

export const THEME_KEY = 'hafize.theme.v1';
export const WEEKDAYS = Object.freeze(['Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt', 'Paz']);
export function resolveTheme(stored: unknown, prefersDark: boolean): ThemeName { if (stored === 'light' || stored === 'dark') return stored; return prefersDark ? 'dark' : 'light'; }
export function createMonthCells(year: number, month: number, selectedDay: number): CalendarCell[] { const first = new Date(year, month, 1); const startOffset = (first.getDay() + 6) % 7; const gridStart = new Date(year, month, 1 - startOffset); return Array.from({ length: 42 }, (_, index) => { const date = new Date(gridStart); date.setDate(gridStart.getDate() + index); return Object.freeze({ day: date.getDate(), month: date.getMonth(), year: date.getFullYear(), outside: date.getMonth() !== month, selected: date.getMonth() === month && date.getDate() === selectedDay }); }); }
export function moveCalendarDate(year: number, month: number, day: number, key: string): Pick<CalendarCell, 'year' | 'month' | 'day'> | null { const date = new Date(year, month, day); if (Number.isNaN(date.getTime())) return null; switch (key) { case 'ArrowLeft': date.setDate(date.getDate() - 1); break; case 'ArrowRight': date.setDate(date.getDate() + 1); break; case 'ArrowUp': date.setDate(date.getDate() - 7); break; case 'ArrowDown': date.setDate(date.getDate() + 7); break; case 'Home': date.setDate(1); break; case 'End': date.setMonth(date.getMonth() + 1, 0); break; default: return null; } return Object.freeze({ year: date.getFullYear(), month: date.getMonth(), day: date.getDate() }); }

function installSidebarDisclosure(documentRef: Document): SidebarController | null {
  const sidebar = documentRef.querySelector<HTMLElement>('#sidebar'); const toggle = documentRef.querySelector<HTMLButtonElement>('#sidebarToggle'); if (!sidebar || !toggle) return null; let open = sidebar.classList.contains('open');
  const render = (next: boolean, focusToggle = false): void => { open = Boolean(next); sidebar.classList.toggle('open', open); toggle.setAttribute('aria-expanded', String(open)); toggle.setAttribute('aria-controls', sidebar.id || 'sidebar'); toggle.setAttribute('aria-label', open ? 'Menüyü kapat' : 'Menüyü aç'); if (focusToggle) toggle.focus(); };
  const onToggle = (event: MouseEvent): void => { event.preventDefault(); event.stopImmediatePropagation(); render(!open); };
  const onKeydown = (event: KeyboardEvent): void => { if (event.key !== 'Escape' || !open) return; event.preventDefault(); render(false, true); };
  toggle.addEventListener('click', onToggle, true); documentRef.addEventListener('keydown', onKeydown); render(open);
  return Object.freeze({ isOpen: () => open, close: () => render(false), destroy: () => { toggle.removeEventListener('click', onToggle, true); documentRef.removeEventListener('keydown', onKeydown); } });
}

export function installChatAccessibility(documentRef: Document): boolean { const stage = documentRef.querySelector<HTMLElement>('.chat-stage'); const messages = documentRef.querySelector<HTMLElement>('#messages'); if (!messages) return false; stage?.removeAttribute('aria-live'); messages.setAttribute('role', 'log'); messages.setAttribute('aria-live', 'polite'); messages.setAttribute('aria-relevant', 'additions text'); messages.setAttribute('aria-atomic', 'false'); messages.setAttribute('aria-label', 'Sohbet mesajları'); return true; }

export function install(documentRef: Document = document, rootRef: UiShellRoot = globalThis as UiShellRoot): UiShellController | null {
  if (!documentRef) return null; const sidebarDisclosure = installSidebarDisclosure(documentRef); installChatAccessibility(documentRef); const html = documentRef.documentElement; const toggle = documentRef.querySelector<HTMLButtonElement>('#themeToggle'); const media = rootRef.matchMedia?.('(prefers-color-scheme: dark)'); let theme = resolveTheme(rootRef.localStorage?.getItem(THEME_KEY), Boolean(media?.matches));
  const paintTheme = (next: ThemeName): void => { theme = next; html.dataset.theme = next; html.style.colorScheme = next; toggle?.setAttribute('aria-pressed', String(next === 'dark')); toggle?.setAttribute('title', next === 'dark' ? 'Gündüz moduna geç' : 'Gece moduna geç'); documentRef.querySelector('meta[name="theme-color"]')?.setAttribute('content', next === 'dark' ? '#202122' : '#f7f5f0'); };
  const onTheme = (): void => { const next: ThemeName = theme === 'dark' ? 'light' : 'dark'; try { rootRef.localStorage?.setItem(THEME_KEY, next); } catch {} paintTheme(next); };
  toggle?.addEventListener('click', onTheme); paintTheme(theme);
  const monthLabel = documentRef.querySelector<HTMLElement>('#calendarMonth'); const calendarGrid = documentRef.querySelector<HTMLElement>('#calendarGrid'); let cursor = new Date(); let selectedDay = cursor.getDate();
  const renderCalendar = (): void => { if (!calendarGrid || !monthLabel) return; monthLabel.textContent = new Intl.DateTimeFormat('tr-TR', { month: 'long', year: 'numeric' }).format(cursor); const cells = createMonthCells(cursor.getFullYear(), cursor.getMonth(), selectedDay); calendarGrid.replaceChildren(...cells.map((cell) => { const button = documentRef.createElement('button'); button.type = 'button'; button.className = `calendar-day${cell.outside ? ' outside' : ''}${cell.selected ? ' selected' : ''}`; button.textContent = String(cell.day); button.tabIndex = cell.selected ? 0 : -1; button.setAttribute('aria-label', `${cell.day} ${cell.month + 1} ${cell.year}`); button.setAttribute('aria-pressed', String(cell.selected)); button.addEventListener('click', () => { cursor = new Date(cell.year, cell.month, 1); selectedDay = cell.day; renderCalendar(); button.focus(); }); button.addEventListener('keydown', (event) => { const next = moveCalendarDate(cell.year, cell.month, cell.day, event.key); if (!next) return; event.preventDefault(); cursor = new Date(next.year, next.month, 1); selectedDay = next.day; renderCalendar(); calendarGrid.querySelector<HTMLButtonElement>('[aria-pressed="true"]')?.focus(); }); return button; })); };
  documentRef.querySelector<HTMLButtonElement>('#calendarPrev')?.addEventListener('click', () => { cursor = new Date(cursor.getFullYear(), cursor.getMonth() - 1, 1); selectedDay = 1; renderCalendar(); }); documentRef.querySelector<HTMLButtonElement>('#calendarNext')?.addEventListener('click', () => { cursor = new Date(cursor.getFullYear(), cursor.getMonth() + 1, 1); selectedDay = 1; renderCalendar(); }); renderCalendar();
  const proxy = documentRef.querySelector<HTMLButtonElement>('#voiceProxy'); const mic = documentRef.querySelector<HTMLButtonElement>('#micBtn'); proxy?.addEventListener('click', () => mic?.click()); const observer = mic ? new MutationObserver(() => { const active = mic.getAttribute('aria-pressed') === 'true'; documentRef.querySelector('.voice-card')?.classList.toggle('listening', active); if (proxy) proxy.textContent = active ? 'Dinlemeyi durdur' : 'Dinlemek için dokun'; }) : null; if (mic && observer) observer.observe(mic, { attributes: true, attributeFilter: ['aria-pressed'] });
  return Object.freeze({ getTheme: () => theme, renderCalendar, sidebarDisclosure, destroy: () => { observer?.disconnect(); sidebarDisclosure?.destroy(); toggle?.removeEventListener('click', onTheme); } });
}

export const HafizeUiShell = Object.freeze({ THEME_KEY, WEEKDAYS, resolveTheme, createMonthCells, moveCalendarDate, installChatAccessibility, install });
const root = globalThis as UiShellRoot; root.HafizeUiShell = HafizeUiShell;
const boot = (): void => { void install(document, root); }; if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot, { once: true }); else boot();
