export const VOICE_INPUT_DEFAULT_LANGUAGE = 'tr-TR';
export interface SpeechRecognitionLike { lang: string; interimResults: boolean; continuous: boolean; maxAlternatives: number; onstart: (() => void) | null; onresult: ((event: SpeechRecognitionEventLike) => void) | null; onerror: ((event: SpeechRecognitionErrorEventLike) => void) | null; onend: (() => void) | null; start: () => void; stop: () => void; abort: () => void; }
export interface SpeechRecognitionEventLike { readonly results?: SpeechResultListLike; readonly resultIndex?: number; }
export interface SpeechResultListLike { readonly length: number; readonly [index: number]: SpeechAlternativeListLike; }
export interface SpeechAlternativeListLike { readonly [index: number]: { readonly transcript?: string } | undefined; }
export interface SpeechRecognitionErrorEventLike { readonly error?: string; }
interface VoiceRoot extends Window { SpeechRecognition?: new () => SpeechRecognitionLike; webkitSpeechRecognition?: new () => SpeechRecognitionLike; }
export interface VoiceInputController { readonly isSupported: boolean; readonly isListening: () => boolean; readonly start: () => void; readonly stop: () => void; readonly destroy: () => void; }

export function getSpeechRecognitionConstructor(root: VoiceRoot = globalThis as VoiceRoot): (new () => SpeechRecognitionLike) | null { return root.SpeechRecognition || root.webkitSpeechRecognition || null; }
export function normalizeTranscript(value: unknown): string { return typeof value === 'string' ? value.replace(/\s+/g, ' ').trim() : ''; }
export function mergeTranscript(prefix: unknown, transcript: unknown, maxLength = 12_000): string { const before = typeof prefix === 'string' ? prefix.replace(/\s+$/g, '') : ''; const spoken = normalizeTranscript(transcript); const joined = before && spoken ? `${before} ${spoken}` : before || spoken; const limit = Number.isInteger(maxLength) && maxLength > 0 ? maxLength : 12_000; return joined.slice(0, limit); }
export function readRecognitionText(event: SpeechRecognitionEventLike | null | undefined): string { if (!event?.results) return ''; const start = Number.isInteger(event.resultIndex) ? Number(event.resultIndex) : 0; const chunks: string[] = []; for (let index = start; index < event.results.length; index += 1) { const transcript = event.results[index]?.[0]?.transcript; if (typeof transcript === 'string') chunks.push(transcript); } return normalizeTranscript(chunks.join(' ')); }
export function mapSpeechError(code: unknown): string { switch (code) { case 'not-allowed': case 'service-not-allowed': return 'Mikrofon izni verilmedi. Tarayıcı izinlerinden mikrofon erişimini kontrol edebilirsin.'; case 'audio-capture': return 'Kullanılabilir bir mikrofon bulunamadı.'; case 'no-speech': return 'Ses algılanmadı. Mikrofonu tekrar deneyebilirsin.'; case 'network': return 'Tarayıcının ses tanıma servisine ulaşılamadı.'; case 'aborted': return ''; default: return 'Sesli giriş tamamlanamadı. Yazmaya devam edebilirsin.'; } }

export function installVoiceInput(documentRef: Document = document, root: VoiceRoot = globalThis as VoiceRoot): VoiceInputController | null {
  const mic = documentRef.querySelector<HTMLButtonElement>('#micBtn'); const input = documentRef.querySelector<HTMLTextAreaElement>('#messageInput'); if (!mic || !input) return null;
  const toast = documentRef.querySelector<HTMLElement>('#toast'); const Recognition = getSpeechRecognitionConstructor(root); let recognition: SpeechRecognitionLike | null = null; let listening = false; let prefix = '';
  const announce = (message: string): void => { if (!toast || !message) return; toast.textContent = message; toast.classList.remove('hidden'); root.setTimeout(() => toast.classList.add('hidden'), 4200); };
  const render = (): void => { mic.disabled = input.disabled; mic.setAttribute('aria-pressed', String(listening)); mic.setAttribute('aria-label', !Recognition ? 'Sesli giriş bu tarayıcıda desteklenmiyor' : listening ? 'Sesli girişi durdur' : 'Sesli giriş'); mic.textContent = listening ? '●' : '◉'; };
  const stop = (): void => { if (!recognition) { listening = false; render(); return; } try { recognition.stop(); } catch { listening = false; recognition = null; render(); } };
  const abort = (): void => { if (!recognition) return; try { recognition.abort(); } catch {} recognition = null; listening = false; render(); };
  const start = (): void => { if (!Recognition || input.disabled || listening) { render(); return; } prefix = input.value; recognition = new Recognition(); recognition.lang = documentRef.documentElement.lang || root.navigator.language || VOICE_INPUT_DEFAULT_LANGUAGE; recognition.interimResults = true; recognition.continuous = false; recognition.maxAlternatives = 1; recognition.onstart = () => { listening = true; render(); announce('Dinleniyor… Metin otomatik gönderilmez.'); }; recognition.onresult = (event) => { const transcript = readRecognitionText(event); if (!transcript) return; input.value = mergeTranscript(prefix, transcript, input.maxLength); input.dispatchEvent(new Event('input', { bubbles: true })); }; recognition.onerror = (event) => { const message = mapSpeechError(event.error); if (message) announce(message); }; recognition.onend = () => { recognition = null; listening = false; render(); if (!documentRef.hidden) input.focus(); }; try { recognition.start(); } catch { recognition = null; listening = false; render(); announce('Sesli giriş başlatılamadı.'); } };
  const onClick = (event: MouseEvent): void => { event.preventDefault(); event.stopImmediatePropagation(); if (listening) stop(); else start(); };
  const onVisibility = (): void => { if (documentRef.hidden) abort(); };
  mic.addEventListener('click', onClick, true); documentRef.addEventListener('visibilitychange', onVisibility); render();
  return Object.freeze({ isSupported: Boolean(Recognition), isListening: () => listening, start, stop, destroy: () => { abort(); mic.removeEventListener('click', onClick, true); documentRef.removeEventListener('visibilitychange', onVisibility); } });
}

export const HafizeVoiceInput = Object.freeze({ getSpeechRecognitionConstructor, normalizeTranscript, mergeTranscript, readRecognitionText, mapSpeechError, installVoiceInput });
const root = globalThis as VoiceRoot; root.document?.addEventListener('DOMContentLoaded', () => { void installVoiceInput(root.document, root); }, { once: true });
