type ModelToolCall = Readonly<{ id: string; name: string; arguments: string }>;
export type NormalizedModelResponse = Readonly<{ content: string; finishReason: string; toolCalls: readonly ModelToolCall[]; usage: Readonly<Record<string, number>> | null; model: string | null; responseId: string | null }>;
const MAX_CONTENT_LENGTH = 64_000;
const MAX_TOOL_CALLS = 16;
const MAX_FINISH_REASON = 80;
const FINISH_REASONS = new Set(['stop', 'length', 'tool_calls', 'content_filter', 'unknown']);
function text(value: unknown, max: number, code: string): string { const result = typeof value === 'string' ? value.trim() : ''; if (result.length > max) throw new Error(code); return result; }
function normalizeContent(content: unknown): string { if (content == null) return ''; if (typeof content !== 'string') throw new Error('INVALID_MODEL_CONTENT'); return text(content, MAX_CONTENT_LENGTH, 'MODEL_CONTENT_TOO_LARGE'); }
function normalizeFinishReason(value: unknown): string { if (value == null) return 'unknown'; if (typeof value !== 'string') throw new Error('INVALID_MODEL_FINISH_REASON'); const raw = text(value, MAX_FINISH_REASON, 'INVALID_MODEL_FINISH_REASON').toLowerCase(); return FINISH_REASONS.has(raw) ? raw : 'unknown'; }
function normalizeUsage(usage: unknown): Readonly<Record<string, number>> | null { if (usage == null) return null; if (!usage || typeof usage !== 'object' || Array.isArray(usage)) throw new Error('INVALID_MODEL_USAGE'); const output: Record<string, number> = {}; for (const field of ['prompt_tokens', 'completion_tokens', 'total_tokens']) { const value = (usage as Record<string, unknown>)[field]; if (value != null && (!Number.isInteger(value) || Number(value) < 0)) throw new Error('INVALID_MODEL_USAGE'); if (value != null) output[field] = Number(value); } return Object.freeze(output); }
function normalizeToolCalls(toolCalls: unknown): readonly ModelToolCall[] { if (toolCalls == null) return Object.freeze([]); if (!Array.isArray(toolCalls) || toolCalls.length > MAX_TOOL_CALLS) throw new Error('INVALID_MODEL_TOOL_CALLS'); return Object.freeze(toolCalls.map((call: any) => { if (!call || typeof call !== 'object' || Array.isArray(call)) throw new Error('INVALID_MODEL_TOOL_CALL'); const source = call.function && typeof call.function === 'object' ? call.function : call; const id = text(call.id, 200, 'INVALID_MODEL_TOOL_CALL_ID'); const name = text(source.name, 120, 'INVALID_MODEL_TOOL_CALL_NAME'); if (!id || !name) throw new Error('INVALID_MODEL_TOOL_CALL'); if (typeof source.arguments !== 'string' || source.arguments.length > 16_384) throw new Error('INVALID_MODEL_TOOL_CALL'); return Object.freeze({ id, name, arguments: source.arguments }); })); }
export function normalizeModelResponse(response: any = {}): NormalizedModelResponse { if (!response || typeof response !== 'object' || Array.isArray(response)) throw new Error('INVALID_MODEL_RESPONSE'); return Object.freeze({ content: normalizeContent(response.content), finishReason: normalizeFinishReason(response.finishReason), toolCalls: normalizeToolCalls(response.toolCalls), usage: normalizeUsage(response.usage), model: response.model == null ? null : text(response.model, 200, 'INVALID_MODEL_NAME'), responseId: response.responseId == null ? null : text(response.responseId, 200, 'INVALID_MODEL_RESPONSE_ID') }); }
export function normalizeNvidiaChatCompletion(response: any = {}): NormalizedModelResponse { if (!response || typeof response !== 'object' || Array.isArray(response)) throw new Error('INVALID_MODEL_RESPONSE'); const choice = Array.isArray(response.choices) ? response.choices[0] : null; const message = choice?.message; if (!message || message.role !== 'assistant') throw new Error('INVALID_MODEL_RESPONSE'); return normalizeModelResponse({ content: message.content, finishReason: choice.finish_reason, toolCalls: message.tool_calls, usage: response.usage, model: response.model, responseId: response.id }); }
export function isTerminalModelResponse(response: any): boolean { const normalized = normalizeModelResponse(response); return normalized.finishReason !== 'tool_calls' && normalized.finishReason !== 'unknown'; }
export const MODEL_RESPONSE_CONTRACT = Object.freeze({ maxContentLength: MAX_CONTENT_LENGTH, maxToolCalls: MAX_TOOL_CALLS, maxToolArgumentLength: 16_384, finishReasons: Object.freeze([...FINISH_REASONS]) });
