const MAX_CONTENT_LENGTH=64_000,MAX_TOOL_CALLS=16,MAX_FINISH_REASON=80;
export type ModelFinishReason='stop'|'length'|'tool_calls'|'content_filter'|'unknown';
export interface ModelToolCall{readonly id:string;readonly name:string;readonly arguments:string;}
export interface NormalizedModelResponse{readonly content:string;readonly finishReason:ModelFinishReason;readonly toolCalls:readonly ModelToolCall[];readonly usage:Readonly<Record<string,number>>|null;readonly model:string|null;readonly responseId:string|null;}
function text(value:unknown,max:number,code:string):string{const result=typeof value==='string'?value.trim():'';if(result.length>max)throw new Error(code);return result;}
function content(value:unknown):string{if(value==null)return '';if(typeof value!=='string')throw new Error('INVALID_MODEL_CONTENT');return text(value,MAX_CONTENT_LENGTH,'MODEL_CONTENT_TOO_LARGE');}
function reason(value:unknown):ModelFinishReason{if(value==null)return'unknown';if(typeof value!=='string')throw new Error('INVALID_MODEL_FINISH_REASON');const r=text(value,MAX_FINISH_REASON,'INVALID_MODEL_FINISH_REASON').toLowerCase();return(['stop','length','tool_calls','content_filter'].includes(r)?r:'unknown') as ModelFinishReason;}
function usage(value:unknown):Readonly<Record<string,number>>|null{if(value==null)return null;if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('INVALID_MODEL_USAGE');const out:Record<string,number>={};for(const key of ['prompt_tokens','completion_tokens','total_tokens']){const n=(value as Record<string,unknown>)[key];if(n!=null&&(!Number.isInteger(n)||Number(n)<0))throw new Error('INVALID_MODEL_USAGE');if(n!=null)out[key]=Number(n);}return Object.freeze(out);}
function calls(value:unknown):readonly ModelToolCall[]{if(value==null)return Object.freeze([]);if(!Array.isArray(value)||value.length>MAX_TOOL_CALLS)throw new Error('INVALID_MODEL_TOOL_CALLS');return Object.freeze(value.map((item)=>{if(!item||typeof item!=='object'||Array.isArray(item))throw new Error('INVALID_MODEL_TOOL_CALL');const call=item as Record<string,unknown>;const source=call.function&&typeof call.function==='object'&&!Array.isArray(call.function)?call.function as Record<string,unknown>:call;const id=text(call.id,200,'INVALID_MODEL_TOOL_CALL_ID');const name=text(source.name,120,'INVALID_MODEL_TOOL_CALL_NAME');const args=source.arguments;if(!id||!name||typeof args!=='string'||args.length>16_384)throw new Error('INVALID_MODEL_TOOL_CALL');return Object.freeze({id,name,arguments:args});}));}
export function normalizeModelResponse(value:unknown={}):NormalizedModelResponse{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('INVALID_MODEL_RESPONSE');const v=value as Record<string,unknown>;return Object.freeze({content:content(v.content),finishReason:reason(v.finishReason),toolCalls:calls(v.toolCalls),usage:usage(v.usage),model:v.model==null?null:text(v.model,200,'INVALID_MODEL_NAME'),responseId:v.responseId==null?null:text(v.responseId,200,'INVALID_MODEL_RESPONSE_ID')});}
export function normalizeNvidiaChatCompletion(value:unknown={}):NormalizedModelResponse{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('INVALID_MODEL_RESPONSE');const v=value as Record<string,unknown>,choice=Array.isArray(v.choices)?v.choices[0]:null,message=choice&&typeof choice==='object'?(choice as Record<string,unknown>).message:null;if(!message||typeof message!=='object'||Array.isArray(message)||(message as Record<string,unknown>).role!=='assistant')throw new Error('INVALID_MODEL_RESPONSE');const c=choice as Record<string,unknown>,m=message as Record<string,unknown>;return normalizeModelResponse({content:m.content,finishReason:c.finish_reason,toolCalls:m.tool_calls,usage:v.usage,model:v.model,responseId:v.id});}
export const MODEL_RESPONSE_CONTRACT=Object.freeze({maxContentLength:MAX_CONTENT_LENGTH,maxToolCalls:MAX_TOOL_CALLS,maxToolArgumentLength:16_384});