export type RuntimeConfig = Readonly<{ host: string; port: number; nodeMajor: number; nvidiaConfigured: boolean; nimBaseUrl: string; upstreamTimeoutMs: number; maxBodyBytes: number; contextLimitTokens: number; scheduleTickMs: number; scheduleRunTimeoutMs: number }>;
export type RuntimeConfigValidation = Readonly<{ ok: boolean; errors: readonly string[] }>;

const DEFAULTS = Object.freeze({ port: 4173, upstreamTimeoutMs: 60_000, maxBodyBytes: 256 * 1024, contextLimitTokens: 128_000, scheduleTickMs: 30_000, scheduleRunTimeoutMs: 120_000 });
function integerEnv(env: NodeJS.ProcessEnv, key: string, fallback: number, min: number, max: number): number { const raw = env[key]; const value = Number.parseInt(raw || '', 10); return Number.isInteger(value) ? Math.min(Math.max(value, min), max) : fallback; }
function majorVersion(value: string): number { const match = /^v?(\d+)/.exec(value); return match ? Number(match[1]) : 0; }
export function readRuntimeConfig(env: NodeJS.ProcessEnv = process.env, nodeVersion: string = process.version): RuntimeConfig {
  return Object.freeze({ host: env.HOST || '127.0.0.1', port: integerEnv(env, 'PORT', DEFAULTS.port, 1, 65_535), nodeMajor: majorVersion(nodeVersion), nvidiaConfigured: Boolean(env.NVIDIA_API_KEY), nimBaseUrl: (env.NIM_BASE_URL || 'https://integrate.api.nvidia.com/v1').replace(/\/+$/, ''), upstreamTimeoutMs: integerEnv(env, 'HAFIZE_UPSTREAM_TIMEOUT_MS', DEFAULTS.upstreamTimeoutMs, 5_000, 300_000), maxBodyBytes: integerEnv(env, 'HAFIZE_MAX_BODY_BYTES', DEFAULTS.maxBodyBytes, 16 * 1024, 2 * 1024 * 1024), contextLimitTokens: integerEnv(env, 'HAFIZE_CONTEXT_LIMIT_TOKENS', DEFAULTS.contextLimitTokens, 16_000, 2_000_000), scheduleTickMs: integerEnv(env, 'HAFIZE_SCHEDULE_TICK_MS', DEFAULTS.scheduleTickMs, 5_000, 300_000), scheduleRunTimeoutMs: integerEnv(env, 'HAFIZE_SCHEDULE_RUN_TIMEOUT_MS', DEFAULTS.scheduleRunTimeoutMs, 10_000, 300_000) });
}
export function validateRuntimeConfig(config: RuntimeConfig): RuntimeConfigValidation { const errors: string[] = []; if (config.nodeMajor < 24) errors.push('NODE_VERSION_TOO_OLD'); if (!config.nimBaseUrl.startsWith('https://')) errors.push('NIM_BASE_URL_MUST_USE_HTTPS'); if (config.upstreamTimeoutMs < 5_000) errors.push('UPSTREAM_TIMEOUT_TOO_LOW'); if (config.maxBodyBytes > 2 * 1024 * 1024) errors.push('BODY_LIMIT_TOO_LARGE'); return Object.freeze({ ok: errors.length === 0, errors: Object.freeze(errors) }); }
export const RUNTIME_CONFIG_DEFAULTS = DEFAULTS;
