// @ts-ignore Transitional legacy agent authorization and skill registry.
import { authorizeAgentTool } from './agent-runtime.mjs';
// @ts-ignore Transitional connector definitions.
import { CANVA_READ_TOOL_DEFINITION } from './canva-read-tool-boundary.mjs';
// @ts-ignore Transitional connector definitions.
import { GMAIL_READ_TOOL_DEFINITION } from './gmail-read-tool-boundary.mjs';
import { normalizeToolCall, parseToolArguments, sanitizeToolError } from './tool-call-boundary.ts';
import { projectSafeToolExecutionResult } from './tool-execution-result-policy.ts';

interface Agent{readonly id:string;readonly name:string;}
interface Context{readonly traceId:string;readonly agent:Agent;readonly registry?:{readonly agents?:readonly Agent[]};readonly nvidiaConfigured?:boolean;readonly githubReadConfigured?:boolean;readonly githubReadFile?:(args:unknown)=>Promise<unknown>;readonly delegateAgent?:(args:unknown)=>Promise<unknown>;readonly approvalGranted?:boolean;readonly canvaReadAuthenticated?:boolean;readonly canvaReadTool?:{execute:(args:unknown)=>Promise<unknown>};readonly gmailReadAuthenticated?:boolean;readonly gmailReadTool?:{execute:(args:unknown)=>Promise<unknown>};readonly skillsRuntime?:{resolveForAgent:(args:unknown)=>unknown};}
type ToolDefinition=Readonly<{type:'function';function:{name:string;description:string;parameters:Record<string,unknown>}}>;
interface ToolEntry{permission:string;definition:ToolDefinition;available?:(context:Context)=>boolean;execute:(args:Record<string,unknown>,context:Context)=>Promise<unknown>;activity:{running:string;success:string;failure:string};}
const definition=(name:string,description:string,properties:Record<string,unknown>):ToolDefinition=>({type:'function',function:{name,description,parameters:{type:'object',properties,additionalProperties:false}}});
const CATALOG=new Map<string,ToolEntry>([
['runtime_status',{permission:'runtime.status',activity:{running:'Runtime durumu kontrol ediliyor',success:'Runtime durumu kontrol edildi',failure:'Runtime durumu kontrol edilemedi'},definition:definition('runtime_status','Hafize runtime durumunu salt-okunur olarak döndürür.',{}),execute:async(_args,context)=>({status:'ok',traceId:context.traceId,agentId:context.agent.id,agentName:context.agent.name,nvidiaConfigured:Boolean(context.nvidiaConfigured),githubReadConfigured:Boolean(context.githubReadConfigured),availableAgents:(context.registry?.agents||[]).map(agent=>({id:agent.id,name:agent.name}))})}],
['agent_delegate',{permission:'agent.delegate',activity:{running:'Uzman ajan çalıştırılıyor',success:'Uzman ajan çalıştırıldı',failure:'Uzman ajan çalıştırılamadı'},definition:definition('agent_delegate','Dar kapsamlı bir görevi uzman Hafize ajanına delege eder.',{agentId:{type:'string'},task:{type:'string'}}),available:context=>typeof context.delegateAgent==='function',execute:async(args,context)=>{const result=await context.delegateAgent!(args) as {ok?:boolean;error?:unknown;value?:unknown};if(result?.ok!==true)throw new Error(typeof result?.error==='string'?result.error:'AGENT_DELEGATION_FAILED');return result.value}}],
['github_read_file',{permission:'repo.read',activity:{running:'GitHub dosyası okunuyor',success:'GitHub dosyası okundu',failure:'GitHub dosyası okunamadı'},definition:definition('github_read_file','İzin verilen GitHub reposundaki bir metin dosyasını salt-okunur getirir.',{repository:{type:'string'},path:{type:'string'},ref:{type:'string'}}),available:context=>Boolean(context.githubReadConfigured&&context.githubReadFile),execute:async(args,context)=>context.githubReadFile!(args)}],
['canva_read',{permission:'connector.canva.read',activity:{running:'Canva verisi okunuyor',success:'Canva verisi okundu',failure:'Canva verisi okunamadı'},definition:CANVA_READ_TOOL_DEFINITION,available:context=>context.canvaReadAuthenticated===true&&Boolean(context.canvaReadTool),execute:async(args,context)=>context.canvaReadTool!.execute(args)}],
['gmail_read',{permission:'connector.gmail.read',activity:{running:'Gmail verisi okunuyor',success:'Gmail verisi okundu',failure:'Gmail verisi okunamadı'},definition:GMAIL_READ_TOOL_DEFINITION,available:context=>context.gmailReadAuthenticated===true&&Boolean(context.gmailReadTool),execute:async(args,context)=>context.gmailReadTool!.execute(args)}],
['skill_invoke',{permission:'skill.invoke',activity:{running:'Hafize skill hazırlanıyor',success:'Hafize skill hazırlandı',failure:'Hafize skill hazırlanamadı'},definition:definition('skill_invoke','Registry içindeki güvenli Hafize skill yapısını çözümler.',{skillId:{type:'string'},args:{type:'object'}}),available:context=>typeof context.skillsRuntime?.resolveForAgent==='function',execute:async(args,context)=>{const invocation=context.skillsRuntime!.resolveForAgent({agent:context.agent,skillId:args.skillId,args:args.args,approvalGranted:context.approvalGranted===true}) as Record<string,unknown>|null;if(!invocation)throw new Error('UNKNOWN_SKILL');return{skill:invocation.name,execution:invocation.execution,model:invocation.model,tools:invocation.tools,arguments:invocation.arguments,prompt:invocation.prompt};}}]
]);
export function getAllowedNvidiaTools(agent:Agent,context:Context,options:{readonly allowedPermissions?:ReadonlySet<string>}={}):readonly ToolDefinition[]{const output:ToolDefinition[]=[];for(const entry of CATALOG.values()){if(entry.available&&!entry.available(context))continue;if(options.allowedPermissions&&!options.allowedPermissions.has(entry.permission))continue;if(authorizeAgentTool(agent,entry.permission).allowed)output.push(entry.definition);}return output;}
export function getPublicToolRunningActivity(name:unknown){const entry=typeof name==='string'?CATALOG.get(name):undefined;return entry?{label:entry.activity.running,state:'running' as const}:null;}
export function getPublicToolActivity(name:unknown,result:unknown){const entry=typeof name==='string'?CATALOG.get(name):undefined;return entry?{label:entry.activity[result&&typeof result==='object'&&(result as {ok?:boolean}).ok===true?'success':'failure'],state:result&&typeof result==='object'&&(result as {ok?:boolean}).ok===true?'success' as const:'failure' as const}:null;}
export async function executeNvidiaToolCall(agent:Agent,toolCall:unknown,context:Context){let normalized;try{normalized=normalizeToolCall(toolCall);}catch(error){return{ok:false as const,error:sanitizeToolError(error).code};}const entry=CATALOG.get(normalized.function.name);if(!entry)return{ok:false as const,error:'UNKNOWN_TOOL'};if(entry.available&&!entry.available(context))return{ok:false as const,error:'TOOL_UNAVAILABLE'};const authorization=authorizeAgentTool(agent,entry.permission,{approvalGranted:Boolean(context.approvalGranted)});if(!authorization.allowed)return{ok:false as const,error:'TOOL_NOT_AUTHORIZED',reason:authorization.reason};let args;try{args=parseToolArguments(normalized.function.arguments);}catch(error){return{ok:false as const,error:sanitizeToolError(error).code};}try{return projectSafeToolExecutionResult({ok:true as const,value:await entry.execute(args,context)});}catch(error){const safe=sanitizeToolError(error);return{ok:false as const,error:safe.code,...(safe.status!==null?{status:safe.status}: {})};}}
export function listToolPermissions(){return[...CATALOG.entries()].map(([name,entry])=>({name,permission:entry.permission}));}
